// modes : echo, tag, agreement
// 'echo' mode prompts must be interesting statements
export const auxiliariesPrompts = {
  1: {
    mode: "echo",
    prompt: "I know how to track deer in the forest.",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["do you", "do you?"],
    negative: false,
  },

  2: {
    mode: "echo",
    prompt: "I like cheese.",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["do you", "do you?"],
    negative: false,
  },
  3: {
    mode: "echo",
    prompt: "I don't like cheese.",
    highlight: "don't",
    tense: "present simple",
    answer: ["don't you", "don't you?"],
    negative: true,
  },
  4: {
    mode: "echo",
    prompt: "I love football.",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["do you", "do you?"],
    negative: false,
  },
  5: {
    mode: "echo",
    prompt: "I hate golf.",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["do you", "do you?"],
    negative: false,
  },
  6: {
    mode: "echo",
    prompt: "I'm a fan of HC Gottéron.",
    highlight: "am",
    tense: "present simple",
    answer: ["are you", "are you?"],
    negative: false,
  },
  7: {
    mode: "echo",
    prompt: "I'm tired of driving in traffic.",
    highlight: "am",
    tense: "present simple",
    answer: ["are you", "are you?"],
    negative: false,
  },
  8: {
    mode: "echo",
    prompt: "I can dance all night.",
    highlight: "can",
    tense: "ability",
    answer: ["can you", "can you?"],
    negative: false,
  },
  9: {
    mode: "echo",
    prompt: "I have an old car.",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["do you", "do you?"],
    negative: false,
  },
  10: {
    mode: "echo",
    prompt: "I won't travel this summer.",
    highlight: "won't",
    tense: "future simple",
    answer: ["won't you", "won't you?"],
    negative: true,
  },
  11: {
    mode: "echo",
    prompt: "I will go skiing this weekend.",
    highlight: "will",
    tense: "future simple",
    answer: ["will you", "will you?"],
    negative: false,
  },
  12: {
    mode: "echo",
    prompt: "I can't cook.",
    highlight: "can't",
    tense: "ability",
    answer: ["can't you", "can't you?"],
    negative: false,
  },
  13: {
    mode: "echo",
    prompt: "I would go to New Zealand if I had the chance.",
    highlight: "would",
    tense: "conditional",
    answer: ["would you", "would you?"],
    negative: false,
  },
  14: {
    mode: "echo",
    prompt: "I wouldn't invest in the stock market.",
    highlight: "wouldn't",
    tense: "conditional",
    answer: ["wouldn't you", "wouldn't you?"],
    negative: true,
  },
  15: {
    mode: "echo",
    prompt: "He coaches a football team.",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["does he", "does he?"],
    negative: false,
  },
  16: {
    mode: "echo",
    prompt: "I can see the future.",
    highlight: "can",
    tense: "ability",
    answer: ["can you", "can you?"],
    negative: false,
  },
  17: {
    mode: "echo",
    prompt: "I'm addicted to the news.",
    highlight: "am",
    tense: "present simple",
    answer: ["are you", "are you?"],
    negative: false,
  },
  18: {
    mode: "echo",
    prompt: "I'm not interested.",
    highlight: "am not",
    tense: "present simple",
    answer: ["aren't you", "aren't you?", "are you not", "are you not?"],
    negative: true,
  },
  19: {
    mode: "echo",
    prompt: "I'll call my parents this weekend.",
    highlight: "will",
    tense: "future simple",
    answer: ["will you", "will you?"],
    negative: false,
  },
  20: {
    mode: "echo",
    prompt: "I won't answer my phone this weekend.",
    highlight: "won't",
    tense: "future simple",
    answer: ["won't you", "won't you?"],
    negative: true,
  },
  21: {
    mode: "echo",
    prompt: "I'd buy a Jaguar.",
    highlight: "would",
    tense: "conditional",
    answer: ["would you", "would you?"],
    negative: false,
  },
  22: {
    mode: "echo",
    prompt: "I wouldn't eat there.",
    highlight: "wouldn't",
    tense: "conditional",
    answer: ["wouldn't you", "wouldn't you?"],
    negative: true,
  },
  23: {
    mode: "echo",
    prompt: "I'm working really hard.",
    highlight: "am",
    tense: "present continuous",
    answer: ["are you", "are you?"],
    negative: false,
  },
  24: {
    mode: "echo",
    prompt: "I'm not feeling well.",
    highlight: "am",
    tense: "present continuous",
    answer: ["aren't you", "aren't you?", "are you not", "are you not?"],
    negative: true,
  },
  25: {
    mode: "echo",
    prompt: "I'm trying to change.",
    highlight: "am",
    tense: "present continuous",
    answer: ["are you", "are you?"],
    negative: false,
  },
  26: {
    mode: "echo",
    prompt: "I'm not speaking to him anymore.",
    highlight: "am",
    tense: "present continuous",
    answer: ["aren't you", "aren't you?", "are you not", "are you not?"],
    negative: true,
  },
  27: {
    mode: "echo",
    prompt: "I was invited.",
    highlight: "hidden auxiliary",
    tense: "past simple",
    answer: ["were you", "were you?"],
    negative: false,
  },
  28: {
    mode: "echo",
    prompt: "I wasn't informed.",
    highlight: "wasn't",
    tense: "past simple",
    answer: ["weren't you", "weren't you?", "were you not", "were you not?"],
    negative: true,
  },
  29: {
    mode: "echo",
    prompt: "I haven't decided yet.",
    highlight: "haven't",
    tense: "present perfect",
    answer: ["haven't you", "haven't you?"],
    negative: true,
  },
  30: {
    mode: "echo",
    prompt: "I have been there many times.",
    highlight: "have",
    tense: "present perfect",
    answer: ["have you", "have you?"],
    negative: false,
  },
  31: {
    mode: "echo",
    prompt: "I've already seen that film.",
    highlight: "have",
    tense: "present perfect",
    answer: ["have you", "have you?"],
    negative: false,
  },
  32: {
    mode: "echo",
    prompt: "I haven't tried it yet.",
    highlight: "haven't",
    tense: "present perfect",
    answer: ["haven't you", "haven't you?"],
    negative: true,
  },
  33: {
    mode: "echo",
    prompt: "I want to relax this weekend.",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["do you", "do you?"],
    negative: false,
  },
  34: {
    mode: "echo",
    prompt: "I don't feel like going.",
    highlight: "don't",
    tense: "present simple",
    answer: ["don't you", "don't you?"],
    negative: true,
  },
  35: {
    mode: "echo",
    prompt: "I feel like a change.",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["do you", "do you?"],
    negative: false,
  },
  36: {
    mode: "echo",
    prompt: "My mother is very intelligent.",
    highlight: "is",
    tense: "present simple",
    answer: ["is she", "is she?"],
    negative: false,
  },
  37: {
    mode: "echo",
    prompt: "I'd definitely take that risk.",
    highlight: "'d",
    tense: "conditional",
    answer: ["would you", "would you?"],
    negative: false,
  },
  38: {
    mode: "echo",
    prompt: "I am moving to New York.",
    highlight: "am",
    tense: "present continuous",
    answer: ["are you", "are you?"],
    negative: false,
  },
  39: {
    mode: "echo",
    prompt: "That is dangerous!",
    highlight: "is",
    tense: "present simple",
    answer: ["is it", "is it?"],
    negative: false,
  },
  40: {
    mode: "echo",
    prompt: "The weather will improve.",
    highlight: "will",
    tense: "future simple",
    answer: ["will it", "will it?"],
    negative: false,
  },
  41: {
    mode: "echo",
    prompt: "It looks good.",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["does it", "does it?"],
    negative: false,
  },
  42: {
    mode: "echo",
    prompt: "I play the piano when nobody's listening.",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["do you", "do you?"],
    negative: false,
  },
  43: {
    mode: "echo",
    prompt: "I build remote-controlled airplanes.",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["do you", "do you?"],
    negative: false,
  },
  44: {
    mode: "echo",
    prompt: "He collects vintage maps.",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["does he", "does he?"],
    negative: false,
  },
  45: {
    mode: "echo",
    prompt: "My mom doesn't drink coffee after noon.",
    highlight: "doesn't",
    tense: "present simple",
    answer: ["doesn't she", "does she not?"],
    negative: true,
  },
  46: {
    mode: "echo",
    prompt: "They are building a treehouse in the backyard.",
    highlight: "are",
    tense: "present continuous",
    answer: ["are they", "are they?"],
    negative: false,
  },
  47: {
    mode: "echo",
    prompt: "I am learning to juggle oranges.",
    highlight: "am",
    tense: "present continuous",
    answer: ["are you", "are you?"],
    negative: false,
  },
  48: {
    mode: "echo",
    prompt: "He isn't paying attention.",
    highlight: "isn't",
    tense: "present continuous",
    answer: ["isn't he", "isn't he?", "is he", "is he?"],
    negative: true,
  },
  49: {
    mode: "echo",
    prompt: "We were watching lightning from the balcony.",
    highlight: "were",
    tense: "past continuous",
    answer: ["were you", "were we"],
    negative: false,
  },
  50: {
    mode: "echo",
    prompt: "I wasn't expecting the concert to be that loud.",
    highlight: "wasn't",
    tense: "past continuous",
    answer: ["weren't you", "weren't you?", "were you not", "were you not?"],
    negative: true,
  },
  51: {
    mode: "echo",
    prompt: "I finished the puzzle before dinner.",
    highlight: "hidden auxiliary",
    tense: "past simple",
    answer: ["did you"],
    negative: false,
  },
  52: {
    mode: "echo",
    prompt: "They didn't hear the announcement.",
    highlight: "didn't",
    tense: "past simple",
    answer: ["didn't they", "didn't they?"],
    negative: true,
  },
  53: {
    mode: "echo",
    prompt: "I've lost my keys again.",
    highlight: "have",
    tense: "present perfect",
    answer: ["have you", "have you?"],
    negative: false,
  },
  54: {
    mode: "echo",
    prompt: "She has already left the office.",
    highlight: "has",
    tense: "present perfect",
    answer: ["has she", "has she?"],
    negative: false,
  },
  55: {
    mode: "echo",
    prompt: "I have changed since you last saw me.",
    highlight: "have",
    tense: "present perfect",
    answer: ["have you"],
    negative: false,
  },
  56: {
    mode: "echo",
    prompt: "I've been working on a secret project.",
    highlight: "have",
    tense: "present perfect continuous",
    answer: ["have you", "have you?"],
    negative: false,
  },
  57: {
    mode: "echo",
    prompt: "He has been running every morning.",
    highlight: "has",
    tense: "present perfect continuous",
    answer: ["has he", "has he?"],
    negative: false,
  },
  58: {
    mode: "echo",
    prompt: "They haven't been sleeping well lately.",
    highlight: "haven't",
    tense: "present perfect continuous",
    answer: ["haven't they", "haven't they?"],
    negative: true,
  },
  59: {
    mode: "echo",
    prompt: "I will try the spicy noodles tomorrow.",
    highlight: "will",
    tense: "future simple",
    answer: ["will you", "will you?"],
    negative: false,
  },
  60: {
    mode: "echo",
    prompt: "She won't remember anything.",
    highlight: "won't",
    tense: "future simple",
    answer: ["won't she", "won't she?"],
    negative: true,
  },
  61: {
    mode: "echo",
    prompt: "We are going to start at sunrise.",
    highlight: "are",
    tense: "future (going to)",
    answer: ["are you", "are you?"],
    negative: false,
  },
  62: {
    mode: "echo",
    prompt: "I am going to fix the bike this afternoon.",
    highlight: "am",
    tense: "future (going to)",
    answer: ["are you", "are you?"],
    negative: false,
  },
  63: {
    mode: "echo",
    prompt: "I can memorize a deck of cards.",
    highlight: "can",
    tense: "ability",
    answer: ["can you", "can you?"],
    negative: false,
  },
  64: {
    mode: "echo",
    prompt: "She can't whistle.",
    highlight: "can't",
    tense: "ability",
    answer: ["can't she", "can't she?"],
    negative: true,
  },
  65: {
    mode: "echo",
    prompt: "You must sign the form before Friday.",
    highlight: "must",
    tense: "obligation",
    answer: ["must I", "must I?"],
    negative: false,
  },
  66: {
    mode: "echo",
    prompt: "He shouldn't enter the lab without gloves.",
    highlight: "shouldn't",
    tense: "advice",
    answer: ["shouldn't he", "shouldn't he?"],
    negative: true,
  },
  67: {
    mode: "echo",
    prompt: "I should call my grandmother more often.",
    highlight: "should",
    tense: "advice",
    answer: ["should you", "should you?"],
    negative: false,
  },
  68: {
    mode: "echo",
    prompt: "They shouldn't park here.",
    highlight: "shouldn't",
    tense: "advice",
    answer: ["shouldn't they", "shouldn't they?"],
    negative: true,
  },
  69: {
    mode: "echo",
    prompt: "I might move to the mountains one day.",
    highlight: "might",
    tense: "possibility",
    answer: ["might you", "might you?"],
    negative: false,
  },
  70: {
    mode: "echo",
    prompt: "She could decide to quit.",
    highlight: "could",
    tense: "possibility",
    answer: ["could she", "could she?"],
    negative: false,
  },
  71: {
    mode: "echo",
    prompt: "I would rather stay in and read.",
    highlight: "would",
    tense: "conditional",
    answer: ["would you", "would you?"],
    negative: false,
  },
  72: {
    mode: "echo",
    prompt: "He wouldn't trade that guitar for anything.",
    highlight: "wouldn't",
    tense: "conditional",
    answer: ["wouldn't he", "wouldn't he?"],
    negative: true,
  },
  73: {
    mode: "echo",
    prompt: "She was born in winter.",
    highlight: "hidden auxiliary",
    tense: "past simple",
    answer: ["was she", "was she?"],
    negative: false,
  },
  74: {
    mode: "echo",
    prompt: "They didn't recognize the actor.",
    highlight: "didn't",
    tense: "past simple",
    answer: ["didn't they", "didn't they?"],
    negative: true,
  },
  75: {
    mode: "echo",
    prompt: "I found a message in a bottle.",
    highlight: "hidden auxiliary",
    tense: "past simple",
    answer: ["did you", "did you?"],
    negative: false,
  },
  76: {
    mode: "echo",
    prompt: "He didn't lock the door.",
    highlight: "didn't",
    tense: "past simple",
    answer: ["didn't he", "didn't he?"],
    negative: true,
  },
  77: {
    mode: "echo",
    prompt: "We met in the park.",
    highlight: "hidden auxiliary",
    tense: "past simple",
    answer: ["did you", "did we"],
    negative: false,
  },
  78: {
    mode: "echo",
    prompt: "I'm always losing my sunglasses.",
    highlight: "am",
    tense: "present continuous",
    answer: ["are you", "are you?"],
    negative: false,
  },
  79: {
    mode: "echo",
    prompt: "I broke it.",
    highlight: "hidden auxiliary",
    tense: "past simple",
    answer: ["did you", "did you?"],
    negative: false,
  },
  80: {
    mode: "echo",
    prompt: "The cat has been staring at the wall for an hour.",
    highlight: "has",
    tense: "present perfect continuous",
    answer: ["has it", "has it?"],
    negative: false,
  },
  81: {
    mode: "echo",
    prompt: "I have never put fries on pizza.",
    highlight: "have",
    tense: "present perfect",
    answer: ["haven't you", "haven't you?", "have you not", "have you not?"],
    negative: true,
  },

  ///// agreement
  82: {
    mode: "agreement",
    prompt: "I love chocolate",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["so do I", "so do I."],
    negative: false,
  },

  83: {
    mode: "agreement",
    prompt: "I like cheese",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["so do I", "so do I."],
    negative: false,
  },
  84: {
    mode: "agreement",
    prompt: "I don't like cheese",
    highlight: "don't",
    tense: "present simple",
    answer: ["neither do I", "neither do I."],
    negative: true,
  },
  85: {
    mode: "agreement",
    prompt: "I love football",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["so do I", "so do I."],
    negative: false,
  },
  86: {
    mode: "agreement",
    prompt: "I hate golf",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["so do I", "so do I."],
    negative: false,
  },
  87: {
    mode: "agreement",
    prompt: "I'm a fan of HC Gottéron",
    highlight: "am",
    tense: "present simple",
    answer: ["so am I", "so am I."],
    negative: false,
  },
  88: {
    mode: "agreement",
    prompt: "I'm tired of driving in traffic",
    highlight: "am",
    tense: "present simple",
    answer: ["so am I", "so am I."],
    negative: false,
  },
  89: {
    mode: "agreement",
    prompt: "I can dance all night",
    highlight: "can",
    tense: "ability",
    answer: ["so can I", "so can I."],
    negative: false,
  },
  90: {
    mode: "agreement",
    prompt: "I have an old car",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["so do I", "so do I."],
    negative: false,
  },
  91: {
    mode: "agreement",
    prompt: "I won't travel this summer",
    highlight: "won't",
    tense: "future simple",
    answer: ["neither will I", "neither will I."],
    negative: true,
  },
  92: {
    mode: "agreement",
    prompt: "I will go skiing this weekend",
    highlight: "will",
    tense: "future simple",
    answer: ["so will I", "so will I."],
    negative: false,
  },
  93: {
    mode: "agreement",
    prompt: "I can't cook",
    highlight: "can't",
    tense: "ability",
    answer: ["neither can I", "neither can I."],
    negative: true,
  },
  94: {
    mode: "agreement",
    prompt: "I should go to the dentist",
    highlight: "should",
    tense: "advice",
    answer: ["so should I", "so should I."],
    negative: false,
  },
  95: {
    mode: "agreement",
    prompt: "I shouldn't eat donuts anymore",
    highlight: "shouldn't",
    tense: "advice",
    answer: ["neither should I", "neither should I."],
    negative: true,
  },
  96: {
    mode: "agreement",
    prompt: "I would go to New Zealand if I had the chance",
    highlight: "would",
    tense: "conditional",
    answer: ["so would I", "so would I."],
    negative: false,
  },
  97: {
    mode: "agreement",
    prompt: "I wouldn't invest in the stock market",
    highlight: "wouldn't",
    tense: "conditional",
    answer: ["neither would I", "neither would I."],
    negative: true,
  },
  98: {
    mode: "agreement",
    prompt: "I can't swim",
    highlight: "can't",
    tense: "ability",
    answer: ["neither can I", "neither can I."],
    negative: true,
  },
  99: {
    mode: "agreement",
    prompt: "I can see the future",
    highlight: "can",
    tense: "ability",
    answer: ["so can I"],
    negative: false,
  },
  100: {
    mode: "agreement",
    prompt: "I should go study now",
    highlight: "should",
    tense: "advice",
    answer: ["so should I"],
    negative: false,
  },
  101: {
    mode: "agreement",
    prompt: "I shouldn't waste my time",
    highlight: "shouldn't",
    tense: "advice",
    answer: ["neither should I"],
    negative: true,
  },
  102: {
    mode: "agreement",
    prompt: "I'm addicted to the news",
    highlight: "am",
    tense: "present simple",
    answer: ["so am I"],
    negative: false,
  },
  103: {
    mode: "agreement",
    prompt: "I'm not interested",
    highlight: "am not",
    tense: "present simple",
    answer: ["neither am I"],
    negative: true,
  },
  104: {
    mode: "agreement",
    prompt: "I'll call my parents this weekend",
    highlight: "will",
    tense: "future simple",
    answer: ["so will I"],
    negative: false,
  },
  105: {
    mode: "agreement",
    prompt: "I won't answer my phone this weekend",
    highlight: "won't",
    tense: "future simple",
    answer: ["neither will I"],
    negative: true,
  },
  106: {
    mode: "agreement",
    prompt: "I'd buy a Jaguar",
    highlight: "would",
    tense: "conditional",
    answer: ["so would I"],
    negative: false,
  },
  107: {
    mode: "agreement",
    prompt: "I wouldn't eat there",
    highlight: "wouldn't",
    tense: "conditional",
    answer: ["neither would I"],
    negative: true,
  },
  108: {
    mode: "agreement",
    prompt: "I'm working really hard",
    highlight: "am",
    tense: "present continuous",
    answer: ["so am I"],
    negative: false,
  },
  109: {
    mode: "agreement",
    prompt: "I'm not feeling well",
    highlight: "am",
    tense: "present continuous",
    answer: ["neither am I"],
    negative: true,
  },
  110: {
    mode: "agreement",
    prompt: "I'm trying to understand",
    highlight: "am",
    tense: "present continuous",
    answer: ["so am I"],
    negative: false,
  },
  111: {
    mode: "agreement",
    prompt: "I'm not doing sports right now",
    highlight: "am",
    tense: "present continuous",
    answer: ["neither am I"],
    negative: true,
  },
  112: {
    mode: "agreement",
    prompt: "I was invited",
    highlight: "hidden auxiliary",
    tense: "past simple",
    answer: ["so was I"],
    negative: false,
  },
  113: {
    mode: "agreement",
    prompt: "I wasn't informed",
    highlight: "wasn't",
    tense: "past simple",
    answer: ["neither was I"],
    negative: true,
  },
  114: {
    mode: "agreement",
    prompt: "I haven't decided yet",
    highlight: "haven't",
    tense: "present perfect",
    answer: ["neither have I"],
    negative: true,
  },
  115: {
    mode: "agreement",
    prompt: "I have been there many times",
    highlight: "have",
    tense: "present perfect",
    answer: ["so have I"],
    negative: false,
  },
  116: {
    mode: "agreement",
    prompt: "I've already seen that film",
    highlight: "have",
    tense: "present perfect",
    answer: ["so have I"],
    negative: false,
  },
  117: {
    mode: "agreement",
    prompt: "I haven't tried it yet",
    highlight: "haven't",
    tense: "present perfect",
    answer: ["neither have I"],
    negative: true,
  },
  118: {
    mode: "agreement",
    prompt: "I want to relax this weekend",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["so do I"],
    negative: false,
  },
  119: {
    mode: "agreement",
    prompt: "I don't feel like going",
    highlight: "don't",
    tense: "present simple",
    answer: ["neither do I"],
    negative: true,
  },
  120: {
    mode: "agreement",
    prompt: "I'd take the risk",
    highlight: "would",
    tense: "conditional",
    answer: ["so would I"],
    negative: false,
  },
  121: {
    mode: "agreement",
    prompt: "I believe in aliens.",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["so do I"],
    negative: false,
  },
  122: {
    mode: "agreement",
    prompt: "I knew the truth.",
    highlight: "hidden auxiliary",
    tense: "past simple",
    answer: ["so did I"],
    negative: false,
  },

// ///// tag
  123: {
    mode: "tag",
    prompt: "It's a lovely day, ___________ ?",
    highlight: "It's",
    tense: "present simple",
    answer: ["isn't it", "is it not"],
    negative: true,
  },

  124: {
    mode: "tag",
    prompt: "You're from Switzerland, ___________ ?",
    highlight: "You're",
    tense: "present simple",
    answer: ["aren't you", "are you not"],
    negative: true,
  },
  125: {
    mode: "tag",
    prompt: "Dinner isn't ready yet, ___________ ?",
    highlight: "isn't",
    tense: "present simple",
    answer: ["is it"],
    negative: false,
  },
  126: {
    mode: "tag",
    prompt: "You live near the lake, ___________ ?",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["don't you", "do you not"],
    negative: true,
  },
  127: {
    mode: "tag",
    prompt: "Your brother doesn't eat meat, ___________ ?",
    highlight: "doesn't",
    tense: "present simple",
    answer: ["does he"],
    negative: false,
  },
  128: {
    mode: "tag",
    prompt: "You have time, ___________ ?",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["don't you", "do you not"],
    negative: true,
  },
  129: {
    mode: "tag",
    prompt: "You don't like olives, ___________ ?",
    highlight: "don't",
    tense: "present simple",
    answer: ["do you"],
    negative: false,
  },
  130: {
    mode: "tag",
    prompt: "Your wife speaks three languages, ___________ ?",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["doesn't she", "does she not"],
    negative: true,
  },
  131: {
    mode: "tag",
    prompt: "Your brother doesn't work on Fridays, ___________ ?",
    highlight: "doesn't",
    tense: "present simple",
    answer: ["does he"],
    negative: false,
  },

  132: {
    mode: "tag",
    prompt: "You were at the meeting, ___________ ?",
    highlight: "were",
    tense: "past simple",
    answer: ["weren't you", "were you not"],
    negative: true,
  },
  133: {
    mode: "tag",
    prompt: "You weren't surprised, ___________ ?",
    highlight: "weren't",
    tense: "past simple",
    answer: ["were you"],
    negative: false,
  },
  134: {
    mode: "tag",
    prompt: "You arrived late, ___________ ?",
    highlight: "hidden auxiliary",
    tense: "past simple",
    answer: ["didn't you", "did you not"],
    negative: true,
  },
  135: {
    mode: "tag",
    prompt: "Claudia didn't call you back, ___________ ?",
    highlight: "didn't",
    tense: "past simple",
    answer: ["did she"],
    negative: false,
  },
  136: {
    mode: "tag",
    prompt: "You forgot your password, ___________ ?",
    highlight: "hidden auxiliary",
    tense: "past simple",
    answer: ["didn't you", "did you not"],
    negative: true,
  },
  137: {
    mode: "tag",
    prompt: "You didn't see the sign, ___________ ?",
    highlight: "didn't",
    tense: "past simple",
    answer: ["did you"],
    negative: false,
  },

  138: {
    mode: "tag",
    prompt: "Leila's working late tonight, ___________ ?",
    highlight: "is",
    tense: "present continuous",
    answer: ["isn't she", "is she not"],
    negative: true,
  },
  139: {
    mode: "tag",
    prompt: "Your cousins aren't coming with us, ___________ ?",
    highlight: "aren't",
    tense: "present continuous",
    answer: ["are they"],
    negative: false,
  },
  140: {
    mode: "tag",
    prompt: "You were studying when I called, ___________ ?",
    highlight: "were",
    tense: "past continuous",
    answer: ["weren't you", "were you not"],
    negative: true,
  },
  141: {
    mode: "tag",
    prompt: "You aren't listening, ___________ ?",
    highlight: "aren't",
    tense: "present continuous",
    answer: ["are you"],
    negative: false,
  },

  142: {
    mode: "tag",
    prompt: "You were watching a film, ___________ ?",
    highlight: "were",
    tense: "past continuous",
    answer: ["weren't you", "were you not"],
    negative: true,
  },
  143: {
    mode: "tag",
    prompt: "There will be snow, ___________ ?",
    highlight: "will",
    tense: "future simple",
    answer: ["won't there", "will there not"],
    negative: true,
  },
  144: {
    mode: "tag",
    prompt: "You were driving too fast, ___________ ?",
    highlight: "were",
    tense: "past continuous",
    answer: ["weren't you", "were you not"],
    negative: true,
  },
  145: {
    mode: "tag",
    prompt: "The boss wasn't joking, ___________ ?",
    highlight: "wasn't",
    tense: "past continuous",
    answer: ["was she", "was he"],
    negative: false,
  },

  146: {
    mode: "tag",
    prompt: "You've finished already, ___________ ?",
    highlight: "have",
    tense: "present perfect",
    answer: ["haven't you", "have you not"],
    negative: true,
  },
  147: {
    mode: "tag",
    prompt: "Your neighbor hasn't paid yet, ___________ ?",
    highlight: "hasn't",
    tense: "present perfect",
    answer: ["has he", "has she"],
    negative: false,
  },
  148: {
    mode: "tag",
    prompt: "I've said this before, ___________ ?",
    highlight: "have",
    tense: "present perfect",
    answer: ["haven't I", "have I not"],
    negative: true,
  },
  149: {
    mode: "tag",
    prompt: "Monica hasn't decided, ___________ ?",
    highlight: "hasn't",
    tense: "present perfect",
    answer: ["has she"],
    negative: false,
  },

  150: {
    mode: "tag",
    prompt: "You've been waiting long, ___________ ?",
    highlight: "have",
    tense: "present perfect continuous",
    answer: ["haven't you", "have you not"],
    negative: true,
  },
  151: {
    mode: "tag",
    prompt: "Your son hasn't been sleeping well, ___________ ?",
    highlight: "hasn't",
    tense: "present perfect continuous",
    answer: ["has he"],
    negative: false,
  },
  152: {
    mode: "tag",
    prompt: "They've been arguing again, ___________ ?",
    highlight: "have",
    tense: "present perfect continuous",
    answer: ["haven't they", "have they not"],
    negative: true,
  },
  153: {
    mode: "tag",
    prompt: "It won't rain, ___________ ?",
    highlight: "won't",
    tense: "future simple",
    answer: ["will it"],
    negative: false,
  },

  154: {
    mode: "tag",
    prompt: "You had seen me before, ___________ ?",
    highlight: "had",
    tense: "past perfect",
    answer: ["hadn't you", "had you not"],
    negative: true,
  },
  155: {
    mode: "tag",
    prompt: "You didn't know, ___________ ?",
    highlight: "didn't",
    tense: "past simple",
    answer: ["did you"],
    negative: false,
  },
  156: {
    mode: "tag",
    prompt: "You live in your mom's basement, ___________ ?",
    highlight: "do",
    tense: "present simple",
    answer: ["don't you", "do you not"],
    negative: true,
  },
  157: {
    mode: "tag",
    prompt: "You lost the money, ___________ ?",
    highlight: "hidden auxiliary",
    tense: "past simple",
    answer: ["didn't you", "did you not"],
    negative: false,
  },

  158: {
    mode: "tag",
    prompt: "You'll be there tomorrow, ___________ ?",
    highlight: "will",
    tense: "future simple",
    answer: ["won't you", "will you not"],
    negative: true,
  },
  159: {
    mode: "tag",
    prompt: "You won't forget, ___________ ?",
    highlight: "won't",
    tense: "future simple",
    answer: ["will you"],
    negative: false,
  },
  160: {
    mode: "tag",
    prompt: "They'll help us, ___________ ?",
    highlight: "will",
    tense: "future simple",
    answer: ["won't they", "will they not"],
    negative: true,
  },
  161: {
    mode: "tag",
    prompt: "She won't complain, ___________ ?",
    highlight: "won't",
    tense: "future simple",
    answer: ["will she"],
    negative: false,
  },

  162: {
    mode: "tag",
    prompt: "You're going to call me, ___________ ?",
    highlight: "are",
    tense: "future (going to)",
    answer: ["aren't you", "are you not"],
    negative: true,
  },
  163: {
    mode: "tag",
    prompt: "He isn't going to join us, ___________ ?",
    highlight: "isn't",
    tense: "future (going to)",
    answer: ["is he"],
    negative: false,
  },
  164: {
    mode: "tag",
    prompt: "They're going to start soon, ___________ ?",
    highlight: "are",
    tense: "future (going to)",
    answer: ["aren't they", "are they not"],
    negative: true,
  },
  165: {
    mode: "tag",
    prompt: "We're going to lose, ___________ ?",
    highlight: "'re",
    tense: "future (going to)",
    answer: ["aren't we", "are we not"],
    negative: true,
  },

  166: {
    mode: "tag",
    prompt: "You can keep a secret, ___________ ?",
    highlight: "can",
    tense: "ability",
    answer: ["can't you", "can you not"],
    negative: true,
  },
  167: {
    mode: "tag",
    prompt: "Your son can't swim, ___________ ?",
    highlight: "can't",
    tense: "ability",
    answer: ["can he"],
    negative: false,
  },
  168: {
    mode: "tag",
    prompt: "I should stop talking now, ___________ ?",
    highlight: "should",
    tense: "recommendation",
    answer: ["shouldn't I", "should I not"],
    negative: true,
  },
  169: {
    mode: "tag",
    prompt: "I shouldn't touch that button, ___________ ?",
    highlight: "shouldn't",
    tense: "recommendation",
    answer: ["should I"],
    negative: false,
  },
  170: {
    mode: "tag",
    prompt: "I should see a doctor, ___________ ?",
    highlight: "should",
    tense: "recommendation",
    answer: ["shouldn't I", "should I not"],
    negative: true,
  },
  171: {
    mode: "tag",
    prompt: "Luke shouldn't drive tonight, ___________ ?",
    highlight: "shouldn't",
    tense: "recommendation",
    answer: ["should he"],
    negative: false,
  },
  172: {
    mode: "tag",
    prompt: "It could rain later, ___________ ?",
    highlight: "could",
    tense: "possibility",
    answer: ["couldn't it", "could it not"],
    negative: true,
  },
  173: {
    mode: "tag",
    prompt: "I could never do that, ___________ ?",
    highlight: "could",
    tense: "possibility",
    answer: ["could I"],
    negative: false,
  },
  174: {
    mode: "tag",
    prompt: "I can park here, ___________ ?",
    highlight: "can",
    tense: "ability",
    answer: ["can't I", "can I not"],
    negative: true,
  },
  175: {
    mode: "tag",
    prompt: "You can't come, ___________ ?",
    highlight: "can't",
    tense: "ability",
    answer: ["can you"],
    negative: false,
  },
  176: {
    mode: "tag",
    prompt: "You would help me, ___________ ?",
    highlight: "would",
    tense: "conditional",
    answer: ["wouldn't you", "would you not"],
    negative: true,
  },
  177: {
    mode: "tag",
    prompt: "You wouldn't lie to me, ___________ ?",
    highlight: "wouldn't",
    tense: "conditional",
    answer: ["would you"],
    negative: false,
  },

  178: {
    mode: "tag",
    prompt: "There is a problem, ___________ ?",
    highlight: "is",
    tense: "present simple",
    answer: ["isn't there", "is there not"],
    negative: true,
  },
  179: {
    mode: "tag",
    prompt: "There isn't any milk left, ___________ ?",
    highlight: "isn't",
    tense: "present simple",
    answer: ["is there"],
    negative: false,
  },
  180: {
    mode: "tag",
    prompt: "This tastes strange, ___________ ?",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["doesn't it", "does it not"],
    negative: true,
  },
  181: {
    mode: "tag",
    prompt: "That didn't work, ___________ ?",
    highlight: "didn't",
    tense: "past simple",
    answer: ["did it"],
    negative: false,
  },
  182: {
    mode: "tag",
    prompt: "You'd love to travel more, ___________ ?",
    highlight: "would",
    tense: "conditional",
    answer: ["wouldn't you", "would you not"],
    negative: true,
  },
  183: {
    mode: "tag",
    prompt: "You won't do that again, ___________ ?",
    highlight: "won't",
    tense: "future",
    answer: ["will you"],
    negative: false,
  },
  184: {
    mode: "tag",
    prompt: "He has to leave early, ___________ ?",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["doesn't he", "does he not"],
    negative: true,
  },
  185: {
    mode: "tag",
    prompt: "She doesn't have to pay today, ___________ ?",
    highlight: "doesn't",
    tense: "present simple",
    answer: ["does she"],
    negative: false,
  },

  186: {
    mode: "tag",
    prompt: "I'm late, ___________ ?",
    highlight: "am",
    tense: "present simple",
    answer: ["aren't I", "am I not"],
    negative: true,
  },
  187: {
    mode: "tag",
    prompt: "I'm not interrupting, ___________ ?",
    highlight: "am not",
    tense: "present continuous",
    answer: ["am I"],
    negative: false,
  },
  188: {
    mode: "tag",
    prompt: "Let's start now, ___________ ?",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["shall we"],
    negative: false,
  },
  189: {
    mode: "tag",
    prompt: "Open the window, ___________ ?",
    highlight: "hidden auxiliary",
    tense: "present simple",
    answer: ["will you", "won't you"],
    negative: false,
  },
  190: {
    mode: "tag",
    prompt: "Don't make a mess, ___________ ?",
    highlight: "don't",
    tense: "present simple",
    answer: ["will you"],
    negative: false,
  },
  191: {
    mode: "tag",
    prompt: "Federer won again, ___________ ?",
    highlight: "hidden auxiliary",
    tense: "past simple",
    answer: ["didn't he", "did he not"],
    negative: true,
  },
  192: {
    mode: "tag",
    prompt: "I should apologize to you, ___________ ?",
    highlight: "should",
    tense: "advice",
    answer: ["shouldn't I", "should I not"],
    negative: true,
  },
  193: {
    mode: "tag",
    prompt: "She used to live here, ___________ ?",
    highlight: "hidden auxiliary",
    tense: "past simple",
    answer: ["didn't she", "did she not"],
    negative: true,
  },
  194: {
    mode: "tag",
    prompt: "I should change my car, ___________ ?",
    highlight: "should",
    tense: "advice",
    answer: ["shouldn't I", "should I not"],
    negative: true,
  },
  195: {
    mode: "tag",
    prompt: "You could fix it, ___________ ?",
    highlight: "could",
    tense: "ability",
    answer: ["couldn't you", "could you not"],
    negative: true,
  },
  196: {
    mode: "tag",
    prompt: "You couldn't find the address, ___________ ?",
    highlight: "couldn't",
    tense: "ability",
    answer: ["could you"],
    negative: false,
  },
  197: {
    mode: "tag",
    prompt: "I'm 100% right, ___________ ?",
    highlight: "'m",
    tense: "present simple",
    answer: ["aren't I", "am I not"],
    negative: true,
  },
  198: {
    mode: "tag",
    prompt: "I'm starting to annoy you, ___________ ?",
    highlight: "'m",
    tense: "present continuous",
    answer: ["aren't I", "am I not"],
    negative: true,
  },
  199: {
    mode: "tag",
    prompt: "We've met before, ___________ ?",
    highlight: "have",
    tense: "present perfect",
    answer: ["haven't we", "have we not"],
    negative: true,
  },
  200: {
    mode: "tag",
    prompt: "She didn't return your call, ___________ ?",
    highlight: "didn't",
    tense: "past simple",
    answer: ["did she"],
    negative: false,
  },
  201: {
    mode: "tag",
    prompt: "You will be done by noon, ___________ ?",
    highlight: "will",
    tense: "future perfect",
    answer: ["won't you", "will you not"],
    negative: true,
  },
  202: {
    mode: "tag",
    prompt: "You won't let me down, ___________ ?",
    highlight: "won't",
    tense: "future perfect",
    answer: ["will you"],
    negative: false,
  },
};