
import type { ComparisonPromptRaw } from "./ComparisonPromptEngine";

export const comparisonPrompts: Record<number, ComparisonPromptRaw> = {
  // ----------------------------
  // ADJECTIVES (1–100)
  // ----------------------------
  1: {
    word: "smart",
    person_A: "Bill",
    person_B: "Jeff",
    answer: { comparative: ["smarter than"], superlative: ["the smartest"], equality: ["as smart as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  2: {
    word: "athletic",
    person_A: "Lebron",
    person_B: "Mike",
    answer: { comparative: ["more athletic"], superlative: ["the most athletic"], equality: ["as athletic as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  3: {
    word: "skilful",
    person_A: "Messi",
    person_B: "Cristiano",
    answer: { comparative: ["more skilful than"], superlative: ["the most skilful"], equality: ["as skilful as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  4: {
    word: "competitive",
    person_A: "Roger",
    person_B: "Rafa",
    answer: { comparative: ["more competitive than"], superlative: ["the most competitive"], equality: ["as competitive as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  5: {
    word: "reliable",
    person_A: "Mercedes",
    person_B: "Renault",
    answer: { comparative: ["more reliable than"], superlative: ["the most reliable"], equality: ["as reliable as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  6: {
    word: "high",
    person_A: "Everest",
    person_B: "Moleson",
    answer: { comparative: ["higher than"], superlative: ["the highest"], equality: ["as high as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  7: {
    word: "beautiful",
    person_A: "Valais",
    person_B: "Fribourg",
    answer: { comparative: ["more beautiful than"], superlative: ["the most beautiful"], equality: ["as beautiful as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  8: {
    word: "crowded",
    person_A: "Bern",
    person_B: "Fribourg",
    answer: { comparative: ["more crowded than"], superlative: ["the most crowded"], equality: ["as crowded as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  9: {
    word: "profitable",
    person_A: "UBS",
    person_B: "Raiffeisen",
    answer: { comparative: ["more profitable than"], superlative: ["the most profitable"], equality: ["as profitable as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  10: {
    word: "efficient",
    person_A: "Airbus",
    person_B: "Boeing",
    answer: { comparative: ["more efficient than"], superlative: ["the most efficient"], equality: ["as efficient as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  11: {
    word: "hard",
    person_A: "concrete",
    person_B: "wood",
    answer: { comparative: ["harder than"], superlative: ["the hardest"], equality: ["as hard as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  12: {
    word: "valuable",
    person_A: "steel",
    person_B: "gold",
    answer: { comparative: ["more valuable than"], superlative: ["the most valuable"], equality: ["as valuable as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },

  13: {
    word: "funny",
    person_A: "Bill",
    person_B: "Jeff",
    answer: { comparative: ["funnier than"], superlative: ["the funniest"], equality: ["as funny as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  14: {
    word: "strong",
    person_A: "Lebron",
    person_B: "Mike",
    answer: { comparative: ["stronger than"], superlative: ["the strongest"], equality: ["as strong as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  15: {
    word: "famous",
    person_A: "Messi",
    person_B: "Cristiano",
    answer: { comparative: ["more famous than"], superlative: ["the most famous"], equality: ["as famous as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  16: {
    word: "focused",
    person_A: "Roger",
    person_B: "Rafa",
    answer: { comparative: ["more focused than"], superlative: ["the most focused"], equality: ["as focused as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  17: {
    word: "luxurious",
    person_A: "Mercedes",
    person_B: "Renault",
    answer: { comparative: ["more luxurious than"], superlative: ["the most luxurious"], equality: ["as luxurious as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  18: {
    word: "cold",
    person_A: "Everest",
    person_B: "Moleson",
    answer: { comparative: ["colder than"], superlative: ["the coldest"], equality: ["as cold as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  19: {
    word: "sunny",
    person_A: "Valais",
    person_B: "Fribourg",
    answer: { comparative: ["sunnier than"], superlative: ["the sunniest"], equality: ["as sunny as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  20: {
    word: "quiet",
    person_A: "Bern",
    person_B: "Fribourg",
    answer: { comparative: ["quieter than"], superlative: ["the quietest"], equality: ["as quiet as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  21: {
    word: "safe",
    person_A: "UBS",
    person_B: "Raiffeisen",
    answer: { comparative: ["safer than"], superlative: ["the safest"], equality: ["as safe as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  22: {
    word: "modern",
    person_A: "Airbus",
    person_B: "Boeing",
    answer: { comparative: ["more modern than"], superlative: ["the most modern"], equality: ["as modern as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  23: {
    word: "heavy",
    person_A: "concrete",
    person_B: "wood",
    answer: { comparative: ["heavier than"], superlative: ["the heaviest"], equality: ["as heavy as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  24: {
    word: "precious",
    person_A: "steel",
    person_B: "gold",
    answer: { comparative: ["more precious than"], superlative: ["the most precious"], equality: ["as precious as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },

  25: {
    word: "kind",
    person_A: "Bill",
    person_B: "Jeff",
    answer: { comparative: ["kinder than"], superlative: ["the kindest"], equality: ["as kind as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  26: {
    word: "good",
    person_A: "Lebron",
    person_B: "Mike",
    answer: { comparative: ["better than"], superlative: ["the best"], equality: ["as good as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  27: {
    word: "popular",
    person_A: "Messi",
    person_B: "Cristiano",
    answer: { comparative: ["more popular than"], superlative: ["the most popular"], equality: ["as popular as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  28: {
    word: "patient",
    person_A: "Roger",
    person_B: "Rafa",
    answer: { comparative: ["more patient than"], superlative: ["the most patient"], equality: ["as patient as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  29: {
    word: "durable",
    person_A: "Mercedes",
    person_B: "Renault",
    answer: { comparative: ["more durable than"], superlative: ["the most durable"], equality: ["as durable as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  30: {
    word: "steep",
    person_A: "Everest",
    person_B: "Moleson",
    answer: { comparative: ["steeper than"], superlative: ["the steepest"], equality: ["as steep as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  31: {
    word: "scenic",
    person_A: "Valais",
    person_B: "Fribourg",
    answer: { comparative: ["more scenic than"], superlative: ["the most scenic"], equality: ["as scenic as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  32: {
    word: "lively",
    person_A: "Bern",
    person_B: "Fribourg",
    answer: { comparative: ["livelier than"], superlative: ["the liveliest"], equality: ["as lively as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  33: {
    word: "stable",
    person_A: "UBS",
    person_B: "Raiffeisen",
    answer: { comparative: ["more stable than"], superlative: ["the most stable"], equality: ["as stable as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  34: {
    word: "comfortable",
    person_A: "Airbus",
    person_B: "Boeing",
    answer: { comparative: ["more comfortable"], superlative: ["the most comfortable"], equality: ["as comfortable as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  35: {
    word: "dense",
    person_A: "concrete",
    person_B: "wood",
    answer: { comparative: ["denser than"], superlative: ["the densest"], equality: ["as dense as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  36: {
    word: "rare",
    person_A: "steel",
    person_B: "gold",
    answer: { comparative: ["rarer than", "more rare than"], superlative: ["the rarest", "the most rare"], equality: ["as rare as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },

  37: {
    word: "brave",
    person_A: "Bill",
    person_B: "Jeff",
    answer: { comparative: ["braver than"], superlative: ["the bravest"], equality: ["as brave as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  38: {
    word: "young",
    person_A: "Lebron",
    person_B: "Mike",
    answer: { comparative: ["younger than"], superlative: ["the youngest"], equality: ["as young as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  39: {
    word: "talented",
    person_A: "Messi",
    person_B: "Cristiano",
    answer: { comparative: ["more talented than"], superlative: ["the most talented"], equality: ["as talented as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  40: {
    word: "fit",
    person_A: "Roger",
    person_B: "Rafa",
    answer: { comparative: ["fitter than"], superlative: ["the fittest"], equality: ["as fit as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  41: {
    word: "stylish",
    person_A: "Mercedes",
    person_B: "Renault",
    answer: { comparative: ["more stylish than"], superlative: ["the most stylish"], equality: ["as stylish as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  42: {
    word: "dangerous",
    person_A: "Everest",
    person_B: "Moleson",
    answer: { comparative: ["more dangerous than"], superlative: ["the most dangerous"], equality: ["as dangerous as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  43: {
    word: "green",
    person_A: "Valais",
    person_B: "Fribourg",
    answer: { comparative: ["greener than"], superlative: ["the greenest"], equality: ["as green as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  44: {
    word: "historic",
    person_A: "Bern",
    person_B: "Fribourg",
    answer: { comparative: ["more historic than"], superlative: ["the most historic"], equality: ["as historic as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  45: {
    word: "transparent",
    person_A: "UBS",
    person_B: "Raiffeisen",
    answer: { comparative: ["more transparent than"], superlative: ["the most transparent"], equality: ["as transparent as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  46: {
    word: "spacious",
    person_A: "Airbus",
    person_B: "Boeing",
    answer: { comparative: ["more spacious than"], superlative: ["the most spacious"], equality: ["as spacious as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  47: {
    word: "rough",
    person_A: "concrete",
    person_B: "wood",
    answer: { comparative: ["rougher than"], superlative: ["the roughest"], equality: ["as rough as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  48: {
    word: "expensive",
    person_A: "steel",
    person_B: "gold",
    answer: { comparative: ["more expensive than"], superlative: ["the most expensive"], equality: ["as expensive as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },

  49: {
    word: "honest",
    person_A: "Bill",
    person_B: "Jeff",
    answer: { comparative: ["more honest than"], superlative: ["the most honest"], equality: ["as honest as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  50: {
    word: "bad",
    person_A: "Lebron",
    person_B: "Mike",
    answer: { comparative: ["worse than"], superlative: ["the worst"], equality: ["as bad as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  51: {
    word: "famous",
    person_A: "Messi",
    person_B: "Cristiano",
    answer: { comparative: ["more famous than"], superlative: ["the most famous"], equality: ["as famous as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  52: {
    word: "humble",
    person_A: "Roger",
    person_B: "Rafa",
    answer: { comparative: ["humbler than", "more humble than"], superlative: ["the humblest", "the most humble"], equality: ["as humble as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  53: {
    word: "powerful",
    person_A: "Mercedes",
    person_B: "Renault",
    answer: { comparative: ["more powerful than"], superlative: ["the most powerful"], equality: ["as powerful as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  54: {
    word: "far",
    person_A: "Everest",
    person_B: "Moleson",
    answer: { comparative: ["farther than", "further than"], superlative: ["the farthest", "the furthest"], equality: ["as far as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  55: {
    word: "warm",
    person_A: "Valais",
    person_B: "Fribourg",
    answer: { comparative: ["warmer than"], superlative: ["the warmest"], equality: ["as warm as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  56: {
    word: "busy",
    person_A: "Bern",
    person_B: "Fribourg",
    answer: { comparative: ["busier than"], superlative: ["the busiest"], equality: ["as busy as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  57: {
    word: "innovative",
    person_A: "UBS",
    person_B: "Raiffeisen",
    answer: { comparative: ["more innovative than"], superlative: ["the most innovative"], equality: ["as innovative as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  58: {
    word: "punctual",
    person_A: "Airbus",
    person_B: "Boeing",
    answer: { comparative: ["more punctual than"], superlative: ["the most punctual"], equality: ["as punctual as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  59: {
    word: "smooth",
    person_A: "concrete",
    person_B: "wood",
    answer: { comparative: ["smoother than"], superlative: ["the smoothest"], equality: ["as smooth as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  60: {
    word: "shiny",
    person_A: "steel",
    person_B: "gold",
    answer: { comparative: ["shinier than"], superlative: ["the shiniest"], equality: ["as shiny as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },

  61: {
    word: "polite",
    person_A: "Bill",
    person_B: "Jeff",
    answer: { comparative: ["politer than", "more polite than"], superlative: ["the politest", "the most polite"], equality: ["as polite as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  62: {
    word: "old",
    person_A: "Lebron",
    person_B: "Mike",
    answer: { comparative: ["older than"], superlative: ["the oldest"], equality: ["as old as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  63: {
    word: "great",
    person_A: "Messi",
    person_B: "Cristiano",
    answer: { comparative: ["greater than"], superlative: ["the greatest"], equality: ["as great as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  64: {
    word: "quick",
    person_A: "Roger",
    person_B: "Rafa",
    answer: { comparative: ["quicker than"], superlative: ["the quickest"], equality: ["as quick as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  65: {
    word: "expensive",
    person_A: "Mercedes",
    person_B: "Renault",
    answer: { comparative: ["more expensive than"], superlative: ["the most expensive"], equality: ["as expensive as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  66: {
    word: "tall",
    person_A: "Everest",
    person_B: "Moleson",
    answer: { comparative: ["taller than"], superlative: ["the tallest"], equality: ["as tall as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  67: {
    word: "clean",
    person_A: "Valais",
    person_B: "Fribourg",
    answer: { comparative: ["cleaner than"], superlative: ["the cleanest"], equality: ["as clean as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  68: {
    word: "small",
    person_A: "Bern",
    person_B: "Fribourg",
    answer: { comparative: ["smaller than"], superlative: ["the smallest"], equality: ["as small as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  69: {
    word: "rich",
    person_A: "UBS",
    person_B: "Raiffeisen",
    answer: { comparative: ["richer than"], superlative: ["the richest"], equality: ["as rich as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  70: {
    word: "big",
    person_A: "Airbus",
    person_B: "Boeing",
    answer: { comparative: ["bigger than"], superlative: ["the biggest"], equality: ["as big as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  71: {
    word: "strong",
    person_A: "concrete",
    person_B: "wood",
    answer: { comparative: ["stronger than"], superlative: ["the strongest"], equality: ["as strong as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  72: {
    word: "cheap",
    person_A: "steel",
    person_B: "gold",
    answer: { comparative: ["cheaper than"], superlative: ["the cheapest"], equality: ["as cheap as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },

  73: {
    word: "easy",
    person_A: "Bill",
    person_B: "Jeff",
    answer: { comparative: ["easier than"], superlative: ["the easiest"], equality: ["as easy as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  74: {
    word: "good",
    person_A: "Lebron",
    person_B: "Mike",
    answer: { comparative: ["better than"], superlative: ["the best"], equality: ["as good as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  75: {
    word: "strong",
    person_A: "Messi",
    person_B: "Cristiano",
    answer: { comparative: ["stronger than"], superlative: ["the strongest"], equality: ["as strong as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  76: {
    word: "tired",
    person_A: "Roger",
    person_B: "Rafa",
    answer: { comparative: ["more tired than"], superlative: ["the most tired"], equality: ["as tired as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  77: {
    word: "safe",
    person_A: "Mercedes",
    person_B: "Renault",
    answer: { comparative: ["safer than"], superlative: ["the safest"], equality: ["as safe as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  78: {
    word: "old",
    person_A: "Everest",
    person_B: "Moleson",
    answer: { comparative: ["older than"], superlative: ["the oldest"], equality: ["as old as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  79: {
    word: "small",
    person_A: "Valais",
    person_B: "Fribourg",
    answer: { comparative: ["smaller than"], superlative: ["the smallest"], equality: ["as small as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  80: {
    word: "old",
    person_A: "Bern",
    person_B: "Fribourg",
    answer: { comparative: ["older than"], superlative: ["the oldest"], equality: ["as old as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  81: {
    word: "secure",
    person_A: "UBS",
    person_B: "Raiffeisen",
    answer: { comparative: ["more secure than"], superlative: ["the most secure"], equality: ["as secure as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  82: {
    word: "safe",
    person_A: "Airbus",
    person_B: "Boeing",
    answer: { comparative: ["safer than"], superlative: ["the safest"], equality: ["as safe as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  83: {
    word: "heavy",
    person_A: "concrete",
    person_B: "wood",
    answer: { comparative: ["heavier than"], superlative: ["the heaviest"], equality: ["as heavy as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  84: {
    word: "valuable",
    person_A: "steel",
    person_B: "gold",
    answer: { comparative: ["more valuable than"], superlative: ["the most valuable"], equality: ["as valuable as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },

  85: {
    word: "happy",
    person_A: "Bill",
    person_B: "Jeff",
    answer: { comparative: ["happier than"], superlative: ["the happiest"], equality: ["as happy as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  86: {
    word: "bad",
    person_A: "Lebron",
    person_B: "Mike",
    answer: { comparative: ["worse than"], superlative: ["the worst"], equality: ["as bad as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  87: {
    word: "good",
    person_A: "Messi",
    person_B: "Cristiano",
    answer: { comparative: ["better than"], superlative: ["the best"], equality: ["as good as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  88: {
    word: "great",
    person_A: "Roger",
    person_B: "Rafa",
    answer: { comparative: ["greater than"], superlative: ["the greatest"], equality: ["as great as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  89: {
    word: "fast",
    person_A: "Mercedes",
    person_B: "Renault",
    answer: { comparative: ["faster than"], superlative: ["the fastest"], equality: ["as fast as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  90: {
    word: "high",
    person_A: "Everest",
    person_B: "Moleson",
    answer: { comparative: ["higher than"], superlative: ["the highest"], equality: ["as high as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  91: {
    word: "warm",
    person_A: "Valais",
    person_B: "Fribourg",
    answer: { comparative: ["warmer than"], superlative: ["the warmest"], equality: ["as warm as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  92: {
    word: "busy",
    person_A: "Bern",
    person_B: "Fribourg",
    answer: { comparative: ["busier than"], superlative: ["the busiest"], equality: ["as busy as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  93: {
    word: "rich",
    person_A: "UBS",
    person_B: "Raiffeisen",
    answer: { comparative: ["richer than"], superlative: ["the richest"], equality: ["as rich as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  94: {
    word: "safe",
    person_A: "Airbus",
    person_B: "Boeing",
    answer: { comparative: ["safer than"], superlative: ["the safest"], equality: ["as safe as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  95: {
    word: "hard",
    person_A: "concrete",
    person_B: "wood",
    answer: { comparative: ["harder than"], superlative: ["the hardest"], equality: ["as hard as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  96: {
    word: "precious",
    person_A: "steel",
    person_B: "gold",
    answer: { comparative: ["more precious than"], superlative: ["the most precious"], equality: ["as precious as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },

  97: {
    word: "busy",
    person_A: "Bill",
    person_B: "Jeff",
    answer: { comparative: ["busier than"], superlative: ["the busiest"], equality: ["as busy as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  98: {
    word: "strong",
    person_A: "Lebron",
    person_B: "Mike",
    answer: { comparative: ["stronger than"], superlative: ["the strongest"], equality: ["as strong as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  99: {
    word: "honest",
    person_A: "Messi",
    person_B: "Cristiano",
    answer: { comparative: ["more honest than"], superlative: ["the most honest"], equality: ["as honest as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },
  100: {
    word: "tough",
    person_A: "Roger",
    person_B: "Rafa",
    answer: { comparative: ["tougher than"], superlative: ["the toughest"], equality: ["as tough as"] },
    negative: false,
    part_of_speech: "adjective",
    prompt: null,
  },

  // ----------------------------
  // ADVERBS (101–200)
  // ----------------------------
  101: { word: "hard", person_A: "Bill", person_B: "Jeff", answer: { comparative: ["harder than"], superlative: ["the hardest"], equality: ["as hard as"] }, negative: false, part_of_speech: "adverb", prompt: "works" },

  102: { word: "slowly", person_A: "Lebron", person_B: "Mike", answer: { comparative: ["more slowly than"], superlative: ["the most slowly"], equality: ["as slowly as"] }, negative: false, part_of_speech: "adverb", prompt: "thinks" },
  103: { word: "well", person_A: "Messi", person_B: "Cristiano", answer: { comparative: ["better than"], superlative: ["the best"], equality: ["as well as"] }, negative: false, part_of_speech: "adverb", prompt: "plays" },
  104: { word: "badly", person_A: "Roger", person_B: "Rafa", answer: { comparative: ["worse than"], superlative: ["the worst"], equality: ["as badly as"] }, negative: false, part_of_speech: "adverb", prompt: "serves" },
  105: { word: "smoothly", person_A: "Mercedes", person_B: "Renault", answer: { comparative: ["more smoothly than"], superlative: ["the most smoothly"], equality: ["as smoothly as"] }, negative: false, part_of_speech: "adverb", prompt: "drives" },
  106: { word: "high", person_A: "Everest", person_B: "Moleson", answer: { comparative: ["higher than"], superlative: ["the highest"], equality: ["as high as"] }, negative: false, part_of_speech: "adverb", prompt: "rises" },
  107: { word: "warmly", person_A: "Valais", person_B: "Fribourg", answer: { comparative: ["more warmly than"], superlative: ["the most warmly"], equality: ["as warmly as"] }, negative: false, part_of_speech: "adverb", prompt: "welcomes" },
  108: { word: "rapidly", person_A: "Bern", person_B: "Fribourg", answer: { comparative: ["more rapidly than"], superlative: ["the most rapidly"], equality: ["as rapidly as"] }, negative: false, part_of_speech: "adverb", prompt: "is growing" },
  109: { word: "securely", person_A: "UBS", person_B: "Raiffeisen", answer: { comparative: ["more securely than"], superlative: ["the most securely"], equality: ["as securely as"] }, negative: false, part_of_speech: "adverb", prompt: "stores data" },
  110: { word: "frequently", person_A: "Airbus", person_B: "Boeing", answer: { comparative: ["more frequently than"], superlative: ["the most frequently"], equality: ["as frequently as"] }, negative: false, part_of_speech: "adverb", prompt: "lands" },
  111: { word: "easily", person_A: "concrete", person_B: "wood", answer: { comparative: ["more easily than"], superlative: ["the most easily"], equality: ["as easily as"] }, negative: false, part_of_speech: "adverb", prompt: "breaks" },
  112: { word: "brightly", person_A: "steel", person_B: "gold", answer: { comparative: ["more brightly than"], superlative: ["the most brightly"], equality: ["as brightly as"] }, negative: false, part_of_speech: "adverb", prompt: "shines" },

  113: { word: "quickly", person_A: "Bill", person_B: "Jeff", answer: { comparative: ["more quickly than"], superlative: ["the most quickly"], equality: ["as quickly as"] }, negative: false, part_of_speech: "adverb", prompt: "thinks" },
  114: { word: "gracefully", person_A: "Lebron", person_B: "Mike", answer: { comparative: ["more gracefully than"], superlative: ["the most gracefully"], equality: ["as gracefully as"] }, negative: false, part_of_speech: "adverb", prompt: "jumps" },
  115: { word: "carelessly", person_A: "Messi", person_B: "Cristiano", answer: { comparative: ["more carelessly than"], superlative: ["the most carelessly"], equality: ["as carelessly as"] }, negative: false, part_of_speech: "adverb", prompt: "defends" },
  116: { word: "accurately", person_A: "Roger", person_B: "Rafa", answer: { comparative: ["more accurately than"], superlative: ["the most accurately"], equality: ["as accurately as"] }, negative: false, part_of_speech: "adverb", prompt: "aims" },
  117: { word: "quietly", person_A: "Mercedes", person_B: "Renault", answer: { comparative: ["more quietly than"], superlative: ["the most quietly"], equality: ["as quietly as"] }, negative: false, part_of_speech: "adverb", prompt: "runs" },
  118: { word: "far", person_A: "Everest", person_B: "Moleson", answer: { comparative: ["farther than", "further than"], superlative: ["the farthest", "the furthest"], equality: ["as far as"] }, negative: false, part_of_speech: "adverb", prompt: "can be seen" },
  119: { word: "deeply", person_A: "Valais", person_B: "Fribourg", answer: { comparative: ["more deeply than"], superlative: ["the most deeply"], equality: ["as deeply as"] }, negative: false, part_of_speech: "adverb", prompt: "surprises visitors" },
  120: { word: "fully", person_A: "Bern", person_B: "Fribourg", answer: { comparative: ["more fully than"], superlative: ["the most fully"], equality: ["as fully as"] }, negative: false, part_of_speech: "adverb", prompt: "entertains guests" },
  121: { word: "clearly", person_A: "UBS", person_B: "Raiffeisen", answer: { comparative: ["more clearly than"], superlative: ["the most clearly"], equality: ["as clearly as"] }, negative: false, part_of_speech: "adverb", prompt: "explains fees" },
  122: { word: "reliably", person_A: "Airbus", person_B: "Boeing", answer: { comparative: ["more reliably than"], superlative: ["the most reliably"], equality: ["as reliably as"] }, negative: false, part_of_speech: "adverb", prompt: "delivers planes" },
  123: { word: "slowly", person_A: "concrete", person_B: "wood", answer: { comparative: ["more slowly than"], superlative: ["the most slowly"], equality: ["as slowly as"] }, negative: false, part_of_speech: "adverb", prompt: "cracks" },
  124: { word: "easily", person_A: "steel", person_B: "gold", answer: { comparative: ["more easily than"], superlative: ["the most easily"], equality: ["as easily as"] }, negative: false, part_of_speech: "adverb", prompt: "melts" },

  125: { word: "quietly", person_A: "Bill", person_B: "Jeff", answer: { comparative: ["more quietly than"], superlative: ["the most quietly"], equality: ["as quietly as"] }, negative: false, part_of_speech: "adverb", prompt: "reads" },
  126: { word: "hard", person_A: "Lebron", person_B: "Mike", answer: { comparative: ["harder than"], superlative: ["the hardest"], equality: ["as hard as"] }, negative: false, part_of_speech: "adverb", prompt: "trains" },
  127: { word: "confidently", person_A: "Messi", person_B: "Cristiano", answer: { comparative: ["more confidently than"], superlative: ["the most confidently"], equality: ["as confidently as"] }, negative: false, part_of_speech: "adverb", prompt: "shoots" },
  128: { word: "calmly", person_A: "Roger", person_B: "Rafa", answer: { comparative: ["more calmly than"], superlative: ["the most calmly"], equality: ["as calmly as"] }, negative: false, part_of_speech: "adverb", prompt: "responds" },
  129: { word: "quickly", person_A: "Mercedes", person_B: "Renault", answer: { comparative: ["more quickly than"], superlative: ["the most quickly"], equality: ["as quickly as"] }, negative: false, part_of_speech: "adverb", prompt: "accelerates" },
  130: { word: "steeply", person_A: "Everest", person_B: "Moleson", answer: { comparative: ["more steeply than"], superlative: ["the most steeply"], equality: ["as steeply as"] }, negative: false, part_of_speech: "adverb", prompt: "falls" },
  131: { word: "easily", person_A: "Valais", person_B: "Fribourg", answer: { comparative: ["more easily than"], superlative: ["the most easily"], equality: ["as easily as"] }, negative: false, part_of_speech: "adverb", prompt: "attracts tourists" },
  132: { word: "slowly", person_A: "Bern", person_B: "Fribourg", answer: { comparative: ["more slowly than"], superlative: ["the most slowly"], equality: ["as slowly as"] }, negative: false, part_of_speech: "adverb", prompt: "changes" },
  133: { word: "honestly", person_A: "UBS", person_B: "Raiffeisen", answer: { comparative: ["more honestly than"], superlative: ["the most honestly"], equality: ["as honestly as"] }, negative: false, part_of_speech: "adverb", prompt: "communicates" },
  134: { word: "safely", person_A: "Airbus", person_B: "Boeing", answer: { comparative: ["more safely than"], superlative: ["the most safely"], equality: ["as safely as"] }, negative: false, part_of_speech: "adverb", prompt: "takes off" },
  135: { word: "stiffly", person_A: "concrete", person_B: "wood", answer: { comparative: ["more stiffly than"], superlative: ["the most stiffly"], equality: ["as stiffly as"] }, negative: false, part_of_speech: "adverb", prompt: "moves" },
  136: { word: "suddenly", person_A: "steel", person_B: "gold", answer: { comparative: ["more suddenly than"], superlative: ["the most suddenly"], equality: ["as suddenly as"] }, negative: false, part_of_speech: "adverb", prompt: "rises in value" },

  137: { word: "politely", person_A: "Bill", person_B: "Jeff", answer: { comparative: ["more politely than"], superlative: ["the most politely"], equality: ["as politely as"] }, negative: false, part_of_speech: "adverb", prompt: "asks" },
  138: { word: "easily", person_A: "Lebron", person_B: "Mike", answer: { comparative: ["more easily than"], superlative: ["the most easily"], equality: ["as easily as"] }, negative: false, part_of_speech: "adverb", prompt: "scores" },
  139: { word: "quickly", person_A: "Messi", person_B: "Cristiano", answer: { comparative: ["more quickly than"], superlative: ["the most quickly"], equality: ["as quickly as"] }, negative: false, part_of_speech: "adverb", prompt: "reacts" },
  140: { word: "accurately", person_A: "Roger", person_B: "Rafa", answer: { comparative: ["more accurately than"], superlative: ["the most accurately"], equality: ["as accurately as"] }, negative: false, part_of_speech: "adverb", prompt: "hits" },
  141: { word: "efficiently", person_A: "Mercedes", person_B: "Renault", answer: { comparative: ["more efficiently than"], superlative: ["the most efficiently"], equality: ["as efficiently as"] }, negative: false, part_of_speech: "adverb", prompt: "uses fuel" },
  142: { word: "constantly", person_A: "Everest", person_B: "Moleson", answer: { comparative: ["more constantly than"], superlative: ["the most constantly"], equality: ["as constantly as"] }, negative: false, part_of_speech: "adverb", prompt: "grows" },
  143: { word: "beautifully", person_A: "Valais", person_B: "Fribourg", answer: { comparative: ["more beautifully than"], superlative: ["the most beautifully"], equality: ["as beautifully as"] }, negative: false, part_of_speech: "adverb", prompt: "is developing" },
  144: { word: "strategically", person_A: "Bern", person_B: "Fribourg", answer: { comparative: ["more strategically than"], superlative: ["the most strategically"], equality: ["as strategically as"] }, negative: false, part_of_speech: "adverb", prompt: "is preparing" },
  145: { word: "quickly", person_A: "UBS", person_B: "Raiffeisen", answer: { comparative: ["more quickly than"], superlative: ["the most quickly"], equality: ["as quickly as"] }, negative: false, part_of_speech: "adverb", prompt: "approves loans" },
  146: { word: "regularly", person_A: "Airbus", person_B: "Boeing", answer: { comparative: ["more regularly than"], superlative: ["the most regularly"], equality: ["as regularly as"] }, negative: false, part_of_speech: "adverb", prompt: "has delays" },
  147: { word: "firmly", person_A: "concrete", person_B: "wood", answer: { comparative: ["more firmly than"], superlative: ["the most firmly"], equality: ["as firmly as"] }, negative: false, part_of_speech: "adverb", prompt: "holds" },
  148: { word: "brightly", person_A: "steel", person_B: "gold", answer: { comparative: ["more brightly than"], superlative: ["the most brightly"], equality: ["as brightly as"] }, negative: false, part_of_speech: "adverb", prompt: "glitters" },

  149: { word: "carefully", person_A: "Bill", person_B: "Jeff", answer: { comparative: ["more carefully than"], superlative: ["the most carefully"], equality: ["as carefully as"] }, negative: false, part_of_speech: "adverb", prompt: "chooses" },
  150: { word: "aggressively", person_A: "Lebron", person_B: "Mike", answer: { comparative: ["more aggressively than"], superlative: ["the most aggressively"], equality: ["as aggressively as"] }, negative: false, part_of_speech: "adverb", prompt: "defends" },
  151: { word: "calmly", person_A: "Messi", person_B: "Cristiano", answer: { comparative: ["more calmly than"], superlative: ["the most calmly"], equality: ["as calmly as"] }, negative: false, part_of_speech: "adverb", prompt: "finishes" },
  152: { word: "politely", person_A: "Roger", person_B: "Rafa", answer: { comparative: ["more politely than"], superlative: ["the most politely"], equality: ["as politely as"] }, negative: false, part_of_speech: "adverb", prompt: "apologizes" },
  153: { word: "quietly", person_A: "Mercedes", person_B: "Renault", answer: { comparative: ["more quietly than"], superlative: ["the most quietly"], equality: ["as quietly as"] }, negative: false, part_of_speech: "adverb", prompt: "runs" },
  154: { word: "dramatically", person_A: "Everest", person_B: "Moleson", answer: { comparative: ["more dramatically than"], superlative: ["the most dramatically"], equality: ["as dramatically as"] }, negative: false, part_of_speech: "adverb", prompt: "rises" },
  155: { word: "reluctantly", person_A: "Valais", person_B: "Fribourg", answer: { comparative: ["more reluctantly than"], superlative: ["the most reluctantly"], equality: ["as reluctantly as"] }, negative: false, part_of_speech: "adverb", prompt: "changes" },
  156: { word: "quickly", person_A: "Bern", person_B: "Fribourg", answer: { comparative: ["more quickly than"], superlative: ["the most quickly"], equality: ["as quickly as"] }, negative: false, part_of_speech: "adverb", prompt: "develops" },
  157: { word: "carefully", person_A: "UBS", person_B: "Raiffeisen", answer: { comparative: ["more carefully than"], superlative: ["the most carefully"], equality: ["as carefully as"] }, negative: false, part_of_speech: "adverb", prompt: "invests" },
  158: { word: "comfortably", person_A: "Airbus", person_B: "Boeing", answer: { comparative: ["more comfortably than"], superlative: ["the most comfortably"], equality: ["as comfortably as"] }, negative: false, part_of_speech: "adverb", prompt: "seats passengers" },
  159: { word: "quickly", person_A: "concrete", person_B: "wood", answer: { comparative: ["more quickly than"], superlative: ["the most quickly"], equality: ["as quickly as"] }, negative: false, part_of_speech: "adverb", prompt: "absorbs water" },
  160: { word: "easily", person_A: "steel", person_B: "gold", answer: { comparative: ["more easily than"], superlative: ["the most easily"], equality: ["as easily as"] }, negative: false, part_of_speech: "adverb", prompt: "is bent" },

  161: { word: "clearly", person_A: "Bill", person_B: "Jeff", answer: { comparative: ["more clearly than"], superlative: ["the most clearly"], equality: ["as clearly as"] }, negative: false, part_of_speech: "adverb", prompt: "explains" },
  162: { word: "quickly", person_A: "Lebron", person_B: "Mike", answer: { comparative: ["more quickly than"], superlative: ["the most quickly"], equality: ["as quickly as"] }, negative: false, part_of_speech: "adverb", prompt: "recovers" },
  163: { word: "powerfully", person_A: "Messi", person_B: "Cristiano", answer: { comparative: ["more powerfully than"], superlative: ["the most powerfully"], equality: ["as powerfully as"] }, negative: false, part_of_speech: "adverb", prompt: "runs" },
  164: { word: "boldly", person_A: "Roger", person_B: "Rafa", answer: { comparative: ["more boldly than"], superlative: ["the most boldly"], equality: ["as boldly as"] }, negative: false, part_of_speech: "adverb", prompt: "attacks" },
  165: { word: "consistently", person_A: "Mercedes", person_B: "Renault", answer: { comparative: ["more consistently than"], superlative: ["the most consistently"], equality: ["as consistently as"] }, negative: false, part_of_speech: "adverb", prompt: "performs" },
  166: { word: "often", person_A: "Everest", person_B: "Moleson", answer: { comparative: ["more often than"], superlative: ["the most often"], equality: ["as often as"] }, negative: false, part_of_speech: "adverb", prompt: "is climbed" },
  167: { word: "smartly", person_A: "Valais", person_B: "Fribourg", answer: { comparative: ["more smartly than"], superlative: ["the most smartly"], equality: ["as smartly as"] }, negative: false, part_of_speech: "adverb", prompt: "invests" },
  168: { word: "massively", person_A: "Bern", person_B: "Fribourg", answer: { comparative: ["more massively than"], superlative: ["the most massively"], equality: ["as massively as"] }, negative: false, part_of_speech: "adverb", prompt: "draws tourists" },
  169: { word: "efficiently", person_A: "UBS", person_B: "Raiffeisen", answer: { comparative: ["more efficiently than"], superlative: ["the most efficiently"], equality: ["as efficiently as"] }, negative: false, part_of_speech: "adverb", prompt: "processes payments" },
  170: { word: "safely", person_A: "Airbus", person_B: "Boeing", answer: { comparative: ["more safely than"], superlative: ["the most safely"], equality: ["as safely as"] }, negative: false, part_of_speech: "adverb", prompt: "flies" },
  171: { word: "quickly", person_A: "concrete", person_B: "wood", answer: { comparative: ["more quickly than"], superlative: ["the most quickly"], equality: ["as quickly as"] }, negative: false, part_of_speech: "adverb", prompt: "heats up" },
  172: { word: "efficiently", person_A: "steel", person_B: "gold", answer: { comparative: ["more efficiently than"], superlative: ["the most efficiently"], equality: ["as efficiently as"] }, negative: false, part_of_speech: "adverb", prompt: "conducts electricity" },

  173: { word: "carefully", person_A: "Bill", person_B: "Jeff", answer: { comparative: ["more carefully than"], superlative: ["the most carefully"], equality: ["as carefully as"] }, negative: false, part_of_speech: "adverb", prompt: "listens" },
  174: { word: "intensely", person_A: "Lebron", person_B: "Mike", answer: { comparative: ["more intensely than"], superlative: ["the most intensely"], equality: ["as intensely as"] }, negative: false, part_of_speech: "adverb", prompt: "trains" },
  175: { word: "quickly", person_A: "Messi", person_B: "Cristiano", answer: { comparative: ["more quickly than"], superlative: ["the most quickly"], equality: ["as quickly as"] }, negative: false, part_of_speech: "adverb", prompt: "accelerates" },
  176: { word: "dominantly", person_A: "Roger", person_B: "Rafa", answer: { comparative: ["more dominantly than"], superlative: ["the most dominantly"], equality: ["as dominantly as"] }, negative: false, part_of_speech: "adverb", prompt: "wins" },
  177: { word: "dominantly", person_A: "Mercedes", person_B: "Renault", answer: { comparative: ["more dominantly than"], superlative: ["the most dominantly"], equality: ["as dominantly as"] }, negative: false, part_of_speech: "adverb", prompt: "performs" },
  178: { word: "dangerously", person_A: "Everest", person_B: "Moleson", answer: { comparative: ["more dangerously than"], superlative: ["the most dangerously"], equality: ["as dangerously as"] }, negative: false, part_of_speech: "adverb", prompt: "erodes" },
  179: { word: "easily", person_A: "Valais", person_B: "Fribourg", answer: { comparative: ["more easily than"], superlative: ["the most easily"], equality: ["as easily as"] }, negative: false, part_of_speech: "adverb", prompt: "is accessed" },
  180: { word: "well", person_A: "Bern", person_B: "Fribourg", answer: { comparative: ["better than"], superlative: ["the best"], equality: ["as well as"] }, negative: false, part_of_speech: "adverb", prompt: "organizes events" },
  181: { word: "securely", person_A: "UBS", person_B: "Raiffeisen", answer: { comparative: ["more securely than"], superlative: ["the most securely"], equality: ["as securely as"] }, negative: false, part_of_speech: "adverb", prompt: "protects accounts" },
  182: { word: "efficiently", person_A: "Airbus", person_B: "Boeing", answer: { comparative: ["more efficiently than"], superlative: ["the most efficiently"], equality: ["as efficiently as"] }, negative: false, part_of_speech: "adverb", prompt: "uses fuel" },
  183: { word: "easily", person_A: "concrete", person_B: "wood", answer: { comparative: ["more easily than"], superlative: ["the most easily"], equality: ["as easily as"] }, negative: false, part_of_speech: "adverb", prompt: "cracks" },
  184: { word: "brightly", person_A: "steel", person_B: "gold", answer: { comparative: ["more brightly than"], superlative: ["the most brightly"], equality: ["as brightly as"] }, negative: false, part_of_speech: "adverb", prompt: "reflects light" },

  185: { word: "quickly", person_A: "Bill", person_B: "Jeff", answer: { comparative: ["more quickly than"], superlative: ["the most quickly"], equality: ["as quickly as"] }, negative: false, part_of_speech: "adverb", prompt: "learns" },
  186: { word: "well", person_A: "Lebron", person_B: "Mike", answer: { comparative: ["better than"], superlative: ["the best"], equality: ["as well as"] }, negative: false, part_of_speech: "adverb", prompt: "shoots" },
  187: { word: "well", person_A: "Messi", person_B: "Cristiano", answer: { comparative: ["better than"], superlative: ["the best"], equality: ["as well as"] }, negative: false, part_of_speech: "adverb", prompt: "dribbles" },
  188: { word: "badly", person_A: "Roger", person_B: "Rafa", answer: { comparative: ["worse than"], superlative: ["the worst"], equality: ["as badly as"] }, negative: false, part_of_speech: "adverb", prompt: "misses" },
  189: { word: "carefully", person_A: "Mercedes", person_B: "Renault", answer: { comparative: ["more carefully than"], superlative: ["the most carefully"], equality: ["as carefully as"] }, negative: false, part_of_speech: "adverb", prompt: "brakes" },
  190: { word: "harshly", person_A: "Everest", person_B: "Moleson", answer: { comparative: ["more harshly than"], superlative: ["the most harshly"], equality: ["as harshly as"] }, negative: false, part_of_speech: "adverb", prompt: "treats climbers" },
  191: { word: "well", person_A: "Valais", person_B: "Fribourg", answer: { comparative: ["better than"], superlative: ["the best"], equality: ["as well as"] }, negative: false, part_of_speech: "adverb", prompt: "maintains infrastructure" },
  192: { word: "well", person_A: "Bern", person_B: "Fribourg", answer: { comparative: ["better than"], superlative: ["the best"], equality: ["as well as"] }, negative: false, part_of_speech: "adverb", prompt: "supports the arts" },
  193: { word: "early", person_A: "UBS", person_B: "Raiffeisen", answer: { comparative: ["earlier than"], superlative: ["the earliest"], equality: ["as early as"] }, negative: false, part_of_speech: "adverb", prompt: "opens" },
  194: { word: "consistently", person_A: "Airbus", person_B: "Boeing", answer: { comparative: ["more consistently than"], superlative: ["the most consistently"] }, negative: false, part_of_speech: "adverb", prompt: "disappoints" },
  195: { word: "easily", person_A: "concrete", person_B: "wood", answer: { comparative: ["more easily than"], superlative: ["the most easily"] }, negative: false, part_of_speech: "adverb", prompt: "splits" },
  196: { word: "expensively", person_A: "steel", person_B: "gold", answer: { comparative: ["more expensively than"], superlative: ["the most expensively"] }, negative: false, part_of_speech: "adverb", prompt: "is priced" },

  197: { word: "quickly", person_A: "Bill", person_B: "Jeff", answer: { comparative: ["more quickly than"], superlative: ["the most quickly"] }, negative: false, part_of_speech: "adverb", prompt: "answers" },
  198: { word: "powerfully", person_A: "Lebron", person_B: "Mike", answer: { comparative: ["more powerfully than"], superlative: ["the most powerfully"] }, negative: false, part_of_speech: "adverb", prompt: "dunks" },
  199: { word: "successfully", person_A: "Messi", person_B: "Cristiano", answer: { comparative: ["more successfully than"], superlative: ["the most successfully"] }, negative: false, part_of_speech: "adverb", prompt: "invests" },
  200: { word: "politely", person_A: "Roger", person_B: "Rafa", answer: { comparative: ["more politely than"], superlative: ["the most politely"] }, negative: false, part_of_speech: "adverb", prompt: "shakes hands" },
};
