// src/assets/scripts/ideaLinker/IdeaLinkerPrompts.ts
//
// Dataset format:
// - top-level keys are "entry ids"
// - each entry contains multiple prompt strings (with ___ blank),
//   a set of possibleLinkers, excludedLinkers, translations,
//   and min/max answers metadata.

export type IdeaLinkerTranslations = Record<string, string[]>;

export type IdeaLinkerEntry = {
  category: string;
  variant: string | null;
  behavior: string;
  possibleLinkers: string[] | null;
  excludedLinkers?: string[] | null;
  translations?: IdeaLinkerTranslations;
  minAnswers?: number;
  maxAnswers?: number;
  prompts: string[];
};

export type IdeaLinkerDataset = Record<string, IdeaLinkerEntry>;

export const ideaLinkerPrompts: IdeaLinkerDataset = {
    "1": {
        category: "cause and effect",
        variant: "effect",
        behavior: "sentence modifier",
        possibleLinkers: ["thus", "therefore", "consequently", "as a result", "hence", "for this reason", "not surprisingly"],
        excludedLinkers: ["so"],
        translations: {
            "French": ["ainsi", "par conséquent", "en conséquence", "c'est pourquoi", "de ce fait"],
            "German": ["somit", "folglich", "infolgedessen", "deshalb", "daher"],
            "Italian": ["quindi", "pertanto", "di conseguenza", "perciò", "dunque"],
        },
        minAnswers: 3,
        maxAnswers: 6,
        prompts: [
            "Students have many exams in a short period. ___, they often fail to learn deeply.",
            "Nights are extremely short during winter. ___, people often feel tired.",
            "The roads are frequently icy in winter. ___, accidents tend to occur on the highway.",
            "It sometimes fails to rain for weeks. ___, many plants dry out completely.",
            "National companies are raising their prices. ___, customers are switching to other brands.",
            "Eleanor studies consistently. ___, she usually performs well on exams.",
            "The chef in this restaurant is highly skilled. ___, the place is fully booked on most nights.",
            "He ignores warning signs. ___, the machine eventually breaks down.",
            "A team invests heavily in marketing. ___, its product gains wider recognition.",
            "A forecast predicts heavy rain. ___, outdoor events are often cancelled.",
            "She skips breakfast. ___, she tends to feel dizzy later in the day.",
            "A team trains intensively. ___, it often achieves strong results.",
            "He doesn’t update his software. ___, his computer becomes vulnerable to viruses.",
            "A teacher explains a concept clearly. ___, students understand it more easily.",
            "They reduce ticket prices. ___, attendance typically increases.",
            "She leaves her phone at home. ___, she cannot contact anyone during the day.",
            "A city improves public transport. ___, traffic congestion decreases over time.",
            "He forgets to lock the door. ___, the wind sometimes blows it open.",
            "A store launches a major promotion. ___, sales usually increase.",
            "She practices the piano daily. ___, her performance steadily improves.",
            "We never ignore client feedback. ___, we work in a continuous improvement cycle.",
            "Fishermen didn't use to check the weather. ___, they often got caught in storms.",
            "They will add more staff during peak hours. ___, service becomes faster.",
            "Many small companies fail to back up their files. ___, the government is considering stricter regulations.",
            "Without space to run, chicken cannot be healthy. ___, a norm on minimum space is being enforced.",
            "The cost of heating oil is rising. ___, countries are looking for alternative energy sources.",
            "Most commerce is now online. ___, companies that don't adapt risk losing customers.",
            "The elections were won by the XYZ party. ___, they now have a majority.",
            "Small companies are much more agile. ___, let's resist the urge to hire too fast.",
            "Companies continue to move away. ___, alternative revenue streams are needed.",
            "Vitamins are destroyed during pasteurization. ___, pasteurized orange juice is basically sugar water.",
            "Stretching after exercise is essential. ___, it is being integrated into P.E. classes.",
            "Whales need warm waters for breeding. ___, they migrate to tropical regions during winter.",
            "Older generations sometimes ignore medical advice. ___, their conditions are harder to treat.",
            "AI improves website design. ___, AI assistants are an indispensable tool.",
            "Traditional PCs are a big investment. ___, fewer people buy them.",
            "Adriano's café regularly introduces new desserts. ___, customers visit more frequently.",
            "Teenagers stay up too late. ___, they struggle to concentrate the next day.",
            "The city is planting more trees in an area. ___, air quality is improving.",
            "Most secret agents don't carry ID. ___, they cannot enter certain buildings."

        ]

    },
    "2": {
        category: "cause and effect",
        variant: "cause",
        behavior: "+ subordinate clause",
        possibleLinkers: ["since", "as", "due to the fact that", "given that", "seeing that", "considering that"],
        excludedLinkers: ["because"],
        translations: {
            "French": ["puisque", "comme", "en raison du fait que", "étant donné que", "vu que", "considérant que"],
            "German": ["da", "weil", "aufgrund der Tatsache, dass", "angesichts der Tatsache, dass", "in Anbetracht der Tatsache, dass"],
            "Italian": ["poiché", "dato che", "a causa del fatto che", "considerando che", "visto che"],
        },
        minAnswers: 2,
        maxAnswers: 3,
        prompts: [
            "The roads were closed ___ a severe storm had damaged several bridges overnight.",
            "The meeting was postponed ___ the key speaker fell ill unexpectedly.",
            "The team cancelled practice ___ the field was completely flooded.",
            "The museum shut down early ___ a power outage affected the entire district.",
            "The flight was delayed ___ heavy fog reduced visibility at the airport.",
            "The restaurant received fewer customers ___ construction blocked the main entrance.",
            "The project took longer than expected ___ several requirements changed mid‑way.",
            "The students struggled with the assignment ___ the instructions were unclear.",
            "The company hired additional staff ___ demand increased sharply.",
            "The event was moved indoors ___ rain was forecast for the afternoon.",
            "The school cancelled outdoor activities ___ temperatures dropped below freezing.",
            "The team lost the match ___ several key players were injured.",
            "The store extended its hours ___ holiday shopping had begun.",
            "The city added more buses ___ traffic congestion was worsening.",
            "The teacher repeated the explanation ___ many students looked confused.",
            "The café introduced new menu items ___ customer feedback requested more variety.",
            "The company upgraded its servers ___ website traffic kept increasing.",
            "The university expanded its library hours ___ exams were approaching.",
            "___ air quality has declined, the school installed air purifiers.",
            "___ several deadlines overlapped, the team revised the schedule.",
            "___ patient numbers were rising, the hospital added more staff.",
            "___ supplies were running low, the store restocked early.",
            "___ sales had dropped suddenly, the manager called an emergency meeting.",
            "___ thunderstorms were expected, the family cancelled their picnic.",
            "___ employees had raised concerns, the company changed its policy.",
            "___ the class needed more practice, the teacher adjusted the lesson plan.",
            "___ several structures were unsafe, the school repaired the playground.",
            "___ customers reported usability issues, the team redesigned the product.",
            "___ commuters requested morning service, the café opened earlier.",
            "___ potholes had become dangerous, the city repaired the roads.",
            "___ several breaches had occurred, the company increased security.",
            "___ performance had declined, the team added extra training sessions.",
            "___ noise levels are too high, the school is introducing new rules.",
            "___ inventory needs to be cleared, the store is offering discounts.",
            "___ student interest has shifted, the university has created new courses.",
            "___ it frequently malfunctions, the team is replacing outdated equipment.",
            "___ older versions are no longer supported, the company is updating its software.",
            "___ many students need extra help, the school is organizing tutoring sessions.",
            "___ pollution levels are rising, the city is planting more trees.",
            "___ final tests revealed several issues, the team postponed the launch."
        ]
    },
    "3": {
        category: "cause and effect",
        variant: "cause",
        behavior: "+ noun phrase",
        possibleLinkers: ["due to", "in view of", "owing to", "on account of", "as a result of", "thanks to", "considering"],
        excludedLinkers: ["because of"],
        translations: {
            "French": ["en raison de", "à cause de", "grâce à", "suite à", "du fait de", "par suite de"],
            "German": ["aufgrund", "wegen", "dank", "infolge", "als Folge von", "durch"],
            "Italian": ["a causa di", "grazie a", "in seguito a", "per effetto di", "a motivo di", "in conseguenza di"],
        },
        minAnswers: 3,
        maxAnswers: 5,
        prompts: [
            "The match was cancelled ___ heavy rain and strong winds.",
            "The store saw fewer customers ___ the ongoing road construction nearby.",
            "The flight was delayed ___ dense fog over the runway.",
            "The picnic was ruined ___ unexpected thunderstorms.",
            "The project fell behind schedule ___ repeated technical issues.",
            "The museum closed early ___ a major power outage in the district.",
            "The team struggled to perform ___ a lack of proper equipment.",
            "The café became popular ___ glowing online reviews.",
            "The company expanded its staff ___ a surge in customer demand.",
            "The meeting was postponed ___ a last‑minute scheduling conflict.",
            "The students were exhausted ___ a week of intensive exams.",
            "The restaurant had to refuse guests ___ limited seating capacity.",
            "The event was moved indoors ___ extreme heat warnings.",
            "The team won the contract ___ their strong proposal.",
            "The school cancelled classes ___ severe winter conditions.",
            "The website crashed ___ unusually high traffic.",
            "The team celebrated ___ their recent victory.",
            "The store extended its hours ___ the holiday rush.",
            "The city improved public transport ___ rising commuter complaints.",
            "The teacher repeated the lesson ___ widespread confusion among students.",
            "The company upgraded its servers ___ frequent system failures.",
            "The hospital added more beds ___ increasing patient numbers.",
            "The team revised the plan ___ new information from the client.",
            "The café opened earlier ___ demand from morning commuters.",
            "The university expanded its library ___ growing student enrollment.",
            "The school installed new ventilation ___ poor air quality reports.",
            "The team postponed the launch ___ unresolved technical problems.",
            "The store offered discounts ___ excess inventory.",
            "The company tightened security ___ recent data breaches.",
            "The team trained harder ___ their disappointing performance last season.",
            "The city planted more trees ___ rising pollution levels.",
            "The school organized tutoring sessions ___ declining test scores.",
            "The company redesigned the product ___ customer feedback.",
            "The team replaced outdated tools ___ frequent malfunctions.",
            "The café introduced healthier options ___ customer requests.",
            "The university created new programs ___ shifting job market trends.",
            "The team added more rehearsals ___ the upcoming performance.",
            "The store restocked early ___ high weekend demand.",
            "The company changed its policy ___ employee concerns.",
            "The event was cancelled ___ low registration numbers."
        ]
    },
    "4": {
        category: "sequence",
        variant: null,
        behavior: "sentence modifier",
        possibleLinkers: ["second", "secondly", "third", "next", "then", "after that", "in addition", "furthermore", "not least", "moreover"],
        excludedLinkers: null,
        translations: {
            "French": [ "deuxièmement", "troisièmement", "ensuite", "après cela", "en outre", "de plus", "notamment", "en plus"],
            "German": [ "zweitens", "drittens", "als Nächstes", "danach", "außerdem", "ferner", "nicht zuletzt", "mehr noch"],
            "Italian": [ "in secondo luogo", "in terzo luogo", "successivamente", "dopo di ciò", "inoltre", "per di più", "non ultimo", "ancora di più"],
        },
        minAnswers: 3,
        maxAnswers: 8,
        prompts: [
            "The proposal offers a clear financial advantage. ___, it strengthens long‑term sustainability.",
            "The new curriculum improves student engagement. ___, it aligns better with modern learning needs.",
            "The report highlights a decline in emissions. ___, it shows progress toward climate targets.",
            "The company reduced operational costs. ___, it increased overall productivity.",
            "The policy encourages healthier habits. ___, it reduces pressure on public healthcare.",
            "The project enhances local infrastructure. ___, it creates new job opportunities.",
            "The study reveals strong customer satisfaction. ___, it identifies areas for further improvement.",
            "The initiative supports small businesses. ___, it boosts regional economic growth.",
            "The plan simplifies administrative procedures. ___, it shortens processing times significantly.",
            "The strategy improves data security. ___, it builds greater user trust.",
            "The new design increases accessibility. ___, it improves the overall user experience.",
            "The research confirms the method’s reliability. ___, it demonstrates its scalability.",
            "The program promotes environmental awareness. ___, it encourages community participation.",
            "The update fixes several major bugs. ___, it introduces useful new features.",
            "The campaign raised public awareness. ___, it inspired concrete action from local groups.",
            "The policy reduces unnecessary paperwork. ___, it frees staff to focus on essential tasks.",
            "The team identified the main risks. ___, they proposed effective mitigation strategies.",
            "The model predicts future trends accurately. ___, it helps organizations plan more effectively.",
            "The framework clarifies responsibilities. ___, it improves collaboration across departments.",
            "The system speeds up data processing. ___, it reduces the likelihood of human error.",
            "The proposal addresses budget limitations. ___, it ensures long‑term financial stability.",
            "The analysis highlights key market opportunities. ___, it outlines potential challenges.",
            "The update enhances platform stability. ___, it improves performance under heavy load.",
            "The new guidelines promote transparency. ___, they strengthen public confidence.",
            "The project supports digital transformation. ___, it modernizes outdated workflows.",
            "The measure reduces energy consumption. ___, it lowers operational costs.",
            "The plan improves communication channels. ___, it reduces misunderstandings between teams.",
            "The study identifies emerging patterns. ___, it suggests promising areas for further research.",
            "The initiative increases student motivation. ___, it fosters a more positive learning environment.",
            "The policy encourages innovation. ___, it accelerates technological development.",
            "The redesign improves navigation. ___, it makes information easier to find.",
            "The proposal enhances workplace safety. ___, it reduces the number of accidents.",
            "The strategy strengthens customer loyalty. ___, it increases long‑term revenue.",
            "The program supports teacher development. ___, it improves classroom outcomes.",
            "The new feature streamlines user workflows. ___, it reduces time spent on repetitive tasks.",
            "The report outlines the main challenges. ___, it offers practical recommendations.",
            "The system improves data accuracy. ___, it enables better decision‑making.",
            "The initiative promotes cultural exchange. ___, it enriches the community experience.",
            "The plan reduces environmental impact. ___, it aligns with sustainability goals.",
            "The proposal clarifies evaluation criteria. ___, it ensures fairer assessments."
        ]
},
    "5": {
        category: "comparison",
        variant: "similarity",
        behavior: "sentence modifier",
        possibleLinkers: ["likewise", "similarly", "In the same way", "In a similar fashion", "Along the same lines"],
        excludedLinkers: ["also", "too", "as well"],
        translations: {
            "French": [ "de même", "similairement", "de la même manière", "de façon similaire", "dans le même ordre d'idées"],
            "German": [ "ebenso", "ähnlich", "auf die gleiche Weise", "in ähnlicher Weise", "in der gleichen Art und Weise"],
            "Italian": [ "allo stesso modo", "similmente", "nella stessa maniera", "in modo simile", "sulla stessa linea"],
        },
        minAnswers: 2,
        maxAnswers: 4,
        prompts: [
            "Vw is pivoting towards electric vehicles. ___, French manufacturers are investing heavily in EV technology.",
"Many cities are expanding their public transport networks. ___, regional authorities are improving rail connections.",
"The company is prioritizing sustainability in its supply chain. ___, its partners are adopting greener logistics.",
"Universities are increasing their focus on digital literacy. ___, high schools are integrating more tech‑based learning.",
"The government is promoting renewable energy projects. ___, private firms are funding large solar installations.",
"The brand is targeting younger consumers with minimalist designs. ___, its competitors are simplifying their product lines.",
"The hospital is modernizing its diagnostic equipment. ___, nearby clinics are upgrading their medical tools.",
"The school is emphasizing collaborative learning. ___, other institutions are encouraging group‑based activities.",
"The airline is reducing its carbon footprint. ___, major shipping companies are adopting cleaner fuels.",
"The museum is redesigning its visitor experience. ___, local galleries are rethinking their exhibition layouts.",
"The bank is investing in cybersecurity. ___, insurance companies are strengthening their digital defenses.",
"The retailer is expanding its online presence. ___, small boutiques are building stronger e‑commerce platforms.",
"The city is improving green spaces. ___, neighboring towns are creating new parks and gardens.",
"The company is offering flexible work arrangements. ___, many organizations are adopting hybrid models.",
"The research team is exploring AI‑driven solutions. ___, industry leaders are experimenting with similar technologies.",
"The school is updating its science curriculum. ___, other districts are revising their STEM programs.",
"The firm is shifting toward remote collaboration tools. ___, its partners are adopting cloud‑based platforms.",
"The city is investing in cultural events. ___, nearby regions are promoting local festivals.",
"The organization is focusing on mental‑health support. ___, other nonprofits are expanding their counseling services.",
"The team is adopting a data‑driven approach. ___, competing groups are relying more on analytics.",
"The company is redesigning its onboarding process. ___, other firms are simplifying their training procedures.",
"The university is strengthening its research partnerships. ___, technical institutes are forming new academic alliances.",
"The café is introducing plant‑based options. ___, restaurants across the city are expanding their vegan menus.",
"The startup is prioritizing user privacy. ___, established tech companies are tightening their data policies.",
"The school is integrating outdoor learning activities. ___, youth programs are incorporating nature‑based education.",
"The brand is focusing on sustainable packaging. ___, other manufacturers are reducing plastic use.",
"The team is adopting agile project management. ___, other departments are shifting to iterative workflows.",
"The city is expanding its recycling program. ___, neighboring municipalities are improving waste‑sorting systems.",
"The company is investing in employee training. ___, its competitors are offering new development programs.",
"The museum is digitizing its collections. ___, libraries are creating online archives.",
"The airline is improving customer service. ___, train operators are enhancing passenger support.",
"The university is promoting interdisciplinary studies. ___, research centers are encouraging cross‑field collaboration.",
"The retailer is reducing energy consumption. ___, supermarkets are upgrading to efficient lighting systems.",
"The team is focusing on long‑term planning. ___, other divisions are adopting multi‑year strategies.",
"The school is strengthening its language programs. ___, community centers are offering more language courses.",
"The company is expanding into international markets. ___, local brands are exploring global partnerships.",
"The city is improving pedestrian safety. ___, suburban areas are redesigning their crosswalks.",
"The firm is adopting transparent reporting practices. ___, industry leaders are publishing detailed accountability reports.",
"The organization is prioritizing diversity initiatives. ___, other institutions are implementing inclusive policies.",
"The startup is refining its customer‑feedback system. ___, established companies are enhancing their review processes."
        ]
    },
    "6": {
        category: "comparison",
        variant: "constrast",
        behavior: "sentence modifier",
        possibleLinkers: ["on the other hand", "in contrast", "conversely", "by contrast"],
        excludedLinkers: ["but"],
        translations: {
            "French": [ "cependant", "d'autre part", "en revanche", "inversement", "alors que"],
            "German": [ "jedoch", "andererseits", "im Gegensatz dazu", "umgekehrt", "während"],
            "Italian": [ "tuttavia", "d'altra parte", "al contrario", "viceversa", "mentre"],
        },
        minAnswers: 2,
        maxAnswers: 4,
        prompts: [
            "Google develops its own AI models in house. Apple, ___, relies heavily on third‑party providers for its AI capabilities.",
"Many European cities are reducing car traffic. Some American cities, ___, continue to expand highway networks.",
"The company focuses on premium products. Its main competitor, ___, targets budget‑conscious consumers.",
"The school emphasizes theoretical knowledge. Vocational programs, ___, prioritize hands‑on experience.",
"The airline invests in customer comfort. Low‑cost carriers, ___, focus primarily on reducing operational expenses.",
"The government is tightening environmental regulations. Several industries, ___, are lobbying for fewer restrictions.",
"The university encourages interdisciplinary research. Traditional institutions, ___, maintain strict departmental boundaries.",
"The brand appeals to younger audiences. Luxury labels, ___, cater mainly to older demographics.",
"The city is expanding green spaces. Industrial regions, ___, are struggling with pollution control.",
"The team prefers long‑term planning. Other departments, ___, rely on short‑term solutions.",
"The retailer invests in physical stores. Online‑only brands, ___, operate without any brick‑and‑mortar presence.",
"The company rewards individual performance. ___, cooperative organizations emphasize collective achievement.",
"The school promotes open‑book assessments. ___, standardized systems rely on strict memorization.",
"Tech startups embrace rapid experimentation. ___, established corporations tend to avoid risky innovation.",
"The museum focuses on contemporary art. ___, historical institutions highlight classical collections.",
"The firm encourages remote work. ___, traditional businesses still require daily office attendance.",
"The city invests heavily in public transport. ___, suburban areas remain dependent on private cars.",
"The team values flexible workflows. ___, more hierarchical groups follow rigid procedures.",
"The café sources ingredients locally. ___, large chains rely on centralized distribution.",
"The organization adopts transparent communication. ___, some competitors keep decisions behind closed doors.",
"The country is increasing renewable energy production. ___, its neighbor continues to rely on coal.",
"The school encourages creative problem‑solving. ___, exam‑driven systems prioritize memorization.",
"The company focuses on long‑term sustainability. ___, short‑term investors prioritize immediate returns.",
"The research highlights positive outcomes. ___, other studies point to significant limitations.",
"The brand markets itself as eco‑friendly. ___, rival companies make no environmental claims.",
"The city invests in cycling infrastructure. ___, rural regions lack safe routes for cyclists.",
"The team adopts a collaborative leadership style. ___, some managers prefer top‑down decision‑making.",
"The university offers flexible degree paths. ___, traditional programs follow fixed course sequences.",
"The company encourages experimentation. ___, more conservative firms avoid untested ideas.",
"The school integrates digital tools into lessons. ___, older institutions still rely on paper‑based materials.",
"The country welcomes immigration. ___, other nations enforce strict border controls.",
"The retailer focuses on personalized service. ___, discount stores prioritize speed over interaction.",
"The team uses data‑driven strategies. ___, creative departments rely more on intuition.",
"The café offers a quiet study environment. ___, nearby bars attract loud evening crowds.",
"The organization invests in long‑term research. ___, startups focus on rapid product releases.",
"The city promotes cultural festivals. ___, industrial towns emphasize economic development over arts.",
"The company adopts ethical sourcing. ___, some competitors choose cheaper suppliers regardless of standards.",
"The school encourages student autonomy. ___, more traditional classrooms rely on teacher‑centered instruction.",
"The country invests in high‑speed rail. ___, its neighbor prioritizes road expansion instead.",
"The firm focuses on premium craftsmanship. ___, mass‑market brands emphasize affordability and scale."
        ]
    },
    7: {
        category: "comparison",
        variant: "constrast",
        behavior: "+ subordinate clause",
        possibleLinkers: ["while", "whereas"],
        excludedLinkers: null,
        translations: {
            "French": [ "tandis que", "alors que"],
            "German": [ "während", "wohingegen"],
            "Italian": [ "mentre", "doveas"],
        },
        minAnswers: 2,
        maxAnswers: 2,
        prompts: [
            "The company invests heavily in research and development, ___ its main competitor focuses more on marketing and sales.",
"The school emphasizes creative thinking, ___ traditional institutions prioritize standardized testing.",
"Many cities are expanding public transport, ___ rural areas remain dependent on private cars.",
"The brand targets younger consumers, ___ its rivals appeal mainly to older demographics.",
"The university encourages interdisciplinary study, ___ technical institutes maintain strict specialization.",
"The airline focuses on passenger comfort, ___ low‑cost carriers prioritize operational efficiency.",
"The government is tightening environmental regulations, ___ some industries argue for more flexibility.",
"The team prefers long‑term planning, ___ other departments rely on short‑term solutions.",
"The retailer invests in physical stores, ___ online‑only brands operate entirely digitally.",
"The museum highlights contemporary art, ___ historical institutions focus on classical works.",
"The company rewards individual performance, ___ cooperative organizations emphasize collective success.",
"The school promotes open‑ended projects, ___ exam‑driven systems emphasize memorization.",
"Tech startups embrace rapid experimentation, ___ established corporations avoid risky innovation.",
"The firm encourages remote work, ___ traditional businesses require daily office presence.",
"The city invests in cycling infrastructure, ___ suburban areas prioritize road expansion.",
"The team values flexible workflows, ___ hierarchical groups follow rigid procedures.",
"The café sources ingredients locally, ___ large chains rely on centralized suppliers.",
"The organization practices transparent communication, ___ competitors keep decisions confidential.",
"The country increases renewable energy production, ___ its neighbor continues to rely on coal.",
"The school encourages creative problem‑solving, ___ standardized programs emphasize correct answers.",
"The company focuses on sustainability, ___ short‑term investors prioritize immediate returns.",
"The research highlights positive outcomes, ___ other studies report significant limitations.",
"The brand markets itself as eco‑friendly, ___ rival companies make no environmental claims.",
"The city expands green spaces, ___ industrial regions struggle with pollution.",
"The team adopts a collaborative leadership style, ___ some managers prefer top‑down control.",
"The university offers flexible degree paths, ___ traditional programs follow fixed sequences.",
"The company encourages experimentation, ___ conservative firms avoid untested ideas.",
"The school integrates digital tools, ___ older institutions rely on paper‑based materials.",
"The country welcomes immigration, ___ other nations enforce strict border controls.",
"The retailer focuses on personalized service, ___ discount stores prioritize speed.",
"The team uses data‑driven strategies, ___ creative departments rely on intuition.",
"The café offers a quiet study environment, ___ nearby bars attract loud evening crowds.",
"The organization invests in long‑term research, ___ startups focus on rapid releases.",
"The city promotes cultural festivals, ___ industrial towns emphasize economic growth.",
"The company adopts ethical sourcing, ___ competitors choose cheaper suppliers.",
"The school encourages student autonomy, ___ traditional classrooms center on teacher control.",
"The country invests in high‑speed rail, ___ its neighbor prioritizes highway expansion.",
"The firm focuses on premium craftsmanship, ___ mass‑market brands emphasize affordability.",
"The team values open discussion, ___ other groups prefer structured decision‑making.",
"The university expands international partnerships, ___ local colleges concentrate on regional needs."

    ],
    },
        8: {
        category: "comparison",
        variant: "constrast",
        behavior: "+ noun phrase",
        possibleLinkers: ["unlike"],
        excludedLinkers: null,
        translations: {
            "French": [ "contrairement à"],
            "German": [ "im Gegensatz zu"],
            "Italian": [ "a differenza di"],
        },
        minAnswers: 1,
        maxAnswers: 1,
        prompts: [
            "___ many of its competitors, the company has maintained a strong commitment to sustainability.",
            "___ traditional institutions, the school encourages flexible and student‑led learning.",
            "___ most tech startups, the firm prioritizes long‑term stability over rapid expansion.",
            "___ previous administrations, the current government is investing heavily in renewable energy.",
            "___ other airlines, this carrier focuses primarily on passenger comfort rather than cost‑cutting.",
            "___ large retail chains, the boutique emphasizes handcrafted and locally sourced products.",
            "___ neighboring cities, the region has not yet implemented a comprehensive recycling program.",
            "___ similar organizations, the nonprofit operates entirely without external funding.",
            "___ many luxury brands, the company keeps its pricing accessible to a wider audience.",
            "___ older models, the new device offers significantly improved battery life.",
            "___ traditional classrooms, this learning environment encourages open discussion and collaboration.",
            "___ other departments, the research team relies heavily on data‑driven decision‑making.",
            "___ most competitors, the brand avoids aggressive advertising campaigns.",
            "___ previous versions, the updated software includes advanced security features.",
            "___ many universities, the institute offers fully customizable degree pathways.",
            "___ other cafés in the area, this one provides dedicated quiet zones for studying.",
            "___ similar projects, this initiative focuses on long‑term community impact rather than short‑term results.",
            "___ many countries in the region, the nation has adopted a highly progressive immigration policy.",
            "___ traditional leadership styles, the team’s approach emphasizes shared responsibility.",
            "___ other transportation systems, the new network operates entirely on renewable energy."
        ]
    },
            9: {
        category: "expansion",
        variant: "exemplification",
        behavior: "sentence modifier",
        possibleLinkers: ["for instance", "concretely", "specifically", "namely"],
        excludedLinkers: ["for example"],
        translations: {
            "French": [ "par exemple", "concrètement", "spécifiquement", "à savoir"],
            "German": [ "zum Beispiel", "konkret", "spezifisch", "nämlich"],
            "Italian": [ "ad esempio", "concretamente", "specificamente", "nello specifico"],
        },
        minAnswers: 3,
        maxAnswers: 4,
        prompts: [    
            "The company has implemented several sustainability initiatives. ___, it has reduced its carbon emissions by 30% in the past five years.",
            "The school offers various extracurricular activities. ___, students can join clubs focused on robotics, debate, and community service.",
            "The city has invested in improving public transportation. ___, it has added new bus routes and expanded the subway system.",
            "The university has strengthened its research programs. ___, it has opened three new interdisciplinary laboratories.",
            "The organization supports community engagement. ___, it funds local youth programs and neighborhood events.",
            "The firm has improved workplace flexibility. ___, employees can now choose between remote, hybrid, and on‑site schedules.",
            "The museum has expanded its educational outreach. ___, it now hosts weekly workshops for children and adults.",
            "The café has diversified its menu. ___, it recently introduced plant‑based meals and specialty teas.",
            "The government is promoting digital inclusion. ___, it provides free Wi‑Fi hotspots in underserved areas.",
            "The team has enhanced its data‑driven approach. ___, it uses predictive analytics to guide strategic decisions.",
            "The retailer has modernized its customer experience. ___, it implemented self‑checkout stations and mobile payment options.",
            "The hospital has upgraded its medical technology. ___, it installed advanced imaging equipment in several departments.",
            "The startup has refined its product offering. ___, it launched a streamlined version of its main app.",
            "The school has improved language learning opportunities. ___, it now offers immersion programs in three languages.",
            "The company has expanded its global presence. ___, it opened new offices in Asia and South America.",
            "The city has prioritized environmental protection. ___, it created new protected green zones around the river.",
            "The brand has strengthened its online identity. ___, it redesigned its website and launched a targeted social media campaign.",
            "The university has broadened student support services. ___, it added mental‑health counseling and academic coaching.",
            "The nonprofit has increased its impact. ___, it distributed over 10,000 meals to families in need last year.",
            "The firm has optimized its logistics network. ___, it consolidated warehouses to reduce delivery times.",
            "The university has expanded its support services. ___, it now provides free tutoring and career counseling.",
            "The company has strengthened its cybersecurity measures. ___, it introduced multi‑factor authentication across all systems.",
            "The city has improved its waste‑management strategy. ___, it launched a composting program for all households.",
            "The school has modernized its science curriculum. ___, it added hands‑on laboratory modules for every grade.",
            "The organization has increased its outreach efforts. ___, it partnered with local shelters to distribute essential supplies.",
            "The firm has enhanced its employee benefits. ___, it now offers extended parental leave and mental‑health coverage.",
            "The museum has broadened its cultural programming. ___, it hosts monthly events featuring international artists.",
            "The startup has optimized its user interface. ___, it simplified navigation and reduced loading times.",
            "The hospital has expanded its emergency services. ___, it opened a new trauma unit with specialized staff.",
            "The retailer has diversified its product range. ___, it added eco‑friendly household items to its catalog.",
            "The government has taken steps to support small businesses. ___, it introduced low‑interest loans for new entrepreneurs.",
            "The team has refined its quality‑control process. ___, it implemented automated testing for all major releases.",
            "The café has improved its customer experience. ___, it created a dedicated workspace area with high‑speed Wi‑Fi.",
            "The university has increased international collaboration. ___, it signed exchange agreements with five new institutions.",
            "The company has streamlined its logistics operations. ___, it consolidated regional warehouses to reduce delivery times.",
            "The school has expanded its arts program. ___, it now offers courses in digital illustration and music production.",
            "The nonprofit has strengthened its volunteer network. ___, it trained over 300 new volunteers this year.",
            "The brand has improved its sustainability practices. ___, it switched to fully recyclable packaging.",
            "The city has upgraded its safety infrastructure. ___, it installed smart traffic lights at major intersections.",
            "The firm has expanded its analytics capabilities. ___, it adopted a new platform for real‑time data monitoring."
        ]
    },
                10: {
        category: "expansion",
        variant: "add details or rephrase",
        behavior: "sentence modifier",
        possibleLinkers: [ "That is", "In other words", "In fact", "Actually", "As a matter of fact", "Concretely", "More specifically", "specifically", "more concretely", "In particular"],
        excludedLinkers: null,
        translations: {
            "French": [ "c'est-à-dire", "en d'autres termes", "en fait", "en réalité", "en effet", "concrètement", "plus précisément", "notamment"],
            "German": [ "das heißt", "mit anderen Worten", "tatsächlich", "eigentlich", "in der Tat", "konkret", "genauer gesagt", "insbesondere"],
            "Italian": [ "cioè", "in altre parole", "in effetti", "in realtà", "a dire il vero", "concretamente", "più specificamente", "in particolare"],
        },
        minAnswers: 4,
        maxAnswers: 6,
        prompts: [
            "The company has made significant progress in sustainability. ___, it has reduced its carbon emissions by 30% in the past five years.",
            "Bonobos are the friendliest apes. ___, they are known for their peaceful social interactions and strong bonds within their groups.",
            "The school has improved its digital infrastructure. ___, every classroom is now equipped with interactive displays and high‑speed internet.",
            "The city has strengthened its public safety measures. ___, it installed smart lighting and expanded community patrols.",
            "The team has refined its development process. ___, it now uses automated testing to catch issues earlier.",
            "The university is committed to widening access. ___, it offers full scholarships to students from underrepresented backgrounds.",
            "The café has shifted toward healthier options. ___, it replaced sugary drinks with fresh juices and herbal teas.",
            "The organization has expanded its outreach. ___, it now supports over 50 community programs across the region.",
            "The retailer has modernized its customer experience. ___, it introduced contactless checkout and personalized recommendations.",
            "The museum has broadened its educational mission. ___, it runs weekly workshops for children and adults.",
            "The company has strengthened its data‑privacy policies. ___, it no longer stores user information beyond what is strictly necessary.",
            "The startup has simplified its product offering. ___, it now focuses on a single core service rather than multiple side features.",
            "The school has enhanced its language program. ___, students can choose from five different foreign languages.",
            "The government has taken steps to support small businesses. ___, it created a grant program for early‑stage entrepreneurs.",
            "The hospital has improved patient care. ___, it added a 24‑hour telemedicine service for urgent consultations.",
            "The brand has clarified its identity. ___, it now positions itself as a leader in minimalist design.",
            "The city has committed to greener mobility. ___, it expanded bike‑sharing stations across all major districts.",
            "The firm has optimized its internal communication. ___, it adopted a unified platform for all teams.",
            "The university has strengthened its research capacity. ___, it hired several internationally recognized experts.",
            "The nonprofit has increased its impact. ___, it provided essential resources to more than 20,000 families last year."
        ]      
    },
              11: {
        category: "counter-expectation",
        variant: null,
        behavior: "sentence modifier",
        possibleLinkers: [ "however", "nevertheless", "nonetheless", "even so", "all the same", "that said", "despite that", "in spite of that", "still", "yet", "and yet"],
        excludedLinkers: null,
        translations: {
            "French": [ "cependant", "néanmoins", "toutefois", "malgré tout", "pourtant", "cela dit", "en dépit de cela", "malgré cela", "toujours", "encore"],
            "German": [ "jedoch", "dennoch", "nichtsdestotrotz", "trotzdem", "gleichwohl", "das gesagt", "trotzdem", "trotz alledem", "immer noch", "noch"],
            "Italian": [ "tuttavia", "nondimeno", "nonostante ciò", "eppure", "comunque", "detto ciò", "nonostante ciò", "malgrado ciò", "ancora", "tuttora"],
        },
        minAnswers: 5,
        maxAnswers: 7,
        prompts: [
            "Gottéron has a great attack. ___, they have struggled defensively in recent seasons.",
            "The school has invested in new technology. ___, some students still prefer traditional learning methods.",
            "The city has improved its public transportation. ___, traffic congestion remains a significant issue.",
            "The company reported record profits this year. ___, employee satisfaction has declined noticeably.",
            "The team trained intensively for the tournament. ___, their performance in the opening match was disappointing.",
            "The government introduced strict environmental regulations. ___, pollution levels have barely changed.",
            "The university expanded its scholarship program. ___, many qualified students remain unable to afford tuition.",
            "The retailer launched a major marketing campaign. ___, sales have not increased as expected.",
            "The hospital upgraded its emergency facilities. ___, waiting times continue to be long.",
            "The brand redesigned its website. ___, users still report difficulties navigating key sections.",
            "The airline improved its customer service training. ___, complaints about delays remain high.",
            "The museum added several new exhibits. ___, visitor numbers have not grown significantly.",
            "The company increased its research budget. ___, innovation output has remained relatively flat.",
            "The school reduced class sizes. ___, academic performance has not improved noticeably.",
            "The city built new bike lanes. ___, many residents continue to rely on cars for short trips.",
            "The team hired several experienced players. ___, their overall results have not improved.",
            "The organization raised substantial funds. ___, its outreach programs remain understaffed.",
            "The café introduced a new menu. ___, regular customers still prefer the old options.",
            "The firm adopted a flexible work policy. ___, some employees feel less connected to their teams.",
            "The country invested heavily in renewable energy. ___, fossil fuels still dominate its energy mix.",
            "The startup received significant venture capital. ___, it struggles to scale its operations.",
            "The school implemented a new curriculum. ___, teachers report that students are overwhelmed.",
            "The company expanded into new markets. ___, its domestic sales have stagnated.",
            "The city renovated several public parks. ___, residents say there are still too few green spaces.",
            "The team analyzed its past mistakes carefully. ___, similar errors continue to occur.",
            "The university improved its mental‑health services. ___, many students hesitate to seek help.",
            "The retailer lowered prices across many categories. ___, customer traffic remains low.",
            "The government increased funding for public transport. ___, service reliability has not improved.",
            "The brand launched a sustainability campaign. ___, critics argue its practices remain insufficient.",
            "The hospital hired more nurses. ___, staff shortages persist during peak hours.",
            "The company simplified its internal processes. ___, employees still find the workflow confusing.",
            "The school added more extracurricular options. ___, participation rates have barely changed.",
            "The city expanded its recycling program. ___, overall waste production continues to rise.",
            "The team developed a new strategy. ___, execution on the field remains inconsistent.",
            "The organization improved its volunteer training. ___, retention rates are still low.",
            "The firm upgraded its cybersecurity systems. ___, several minor breaches were reported last quarter.",
            "The university increased its international partnerships. ___, student exchange numbers remain modest.",
            "The café renovated its interior. ___, customer reviews mention that the atmosphere feels unchanged.",
            "The company introduced a four‑day workweek. ___, productivity levels have not increased as expected.",
            "The city launched an anti‑pollution initiative. ___, air quality has shown little improvement."
                    ]
},
12: {
        category: "counter-expectation",
        variant: null,
        behavior: "+ noun phrase",
        possibleLinkers: [ "despite", "in spite of"],
        excludedLinkers: null,
        translations: {
            "French": [ "malgré", "en dépit de"],
            "German": [ "trotz"],
            "Italian": [ "nonostante", "malgrado"],
        },
        minAnswers: 2,
        maxAnswers: 2,
        prompts: [
            "___ the company’s efforts to reduce emissions, its carbon footprint has increased due to rapid growth.",
            "___ the school’s investment in digital tools, many students still prefer pen and paper for note‑taking.",
            "___ the city’s major infrastructure upgrades, traffic congestion remains a daily challenge.",
            "___ the team’s intensive training sessions, their performance in competition has not improved.",
            "___ the government’s strict regulations, pollution levels have barely decreased.",
            "___ the university’s expanded scholarship program, many students still struggle to afford tuition.",
            "___ the retailer’s aggressive marketing campaign, sales have remained flat.",
            "___ the hospital’s new emergency facilities, waiting times continue to be long.",
            "___ the brand’s website redesign, users still report navigation issues.",
            "___ the airline’s customer service improvements, complaints about delays remain high.",
            "___ the museum’s new exhibits, visitor numbers have not increased significantly.",
            "___ the company’s increased research budget, innovation output has stayed relatively low.",
            "___ the school’s reduced class sizes, academic performance has not improved noticeably.",
            "___ the city’s investment in cycling infrastructure, most residents continue to rely on cars.",
            "___ the team’s new strategy, the same mistakes keep appearing in matches.",
            "___ the organization’s successful fundraising efforts, its programs remain understaffed.",
            "___ the café’s updated menu, regular customers still prefer the older options.",
            "___ the firm’s flexible work policy, some employees feel disconnected from their teams.",
            "___ the country’s investment in renewable energy, fossil fuels still dominate its energy mix.",
            "___ the startup’s significant venture funding, it struggles to scale its operations."

        ]
    },
    13: {
        category: "counter-expectation",
        variant: null,
        behavior: "+ subordinate clause",
        possibleLinkers: [ "although", "even though", "though"],
        excludedLinkers: null,
        translations: {
            "French": [ "bien que", "même si", "malgré que"],
            "German": [ "obwohl", "auch wenn"],
            "Italian": [ "anche se", "nonostante"],
        },
        minAnswers: 2,
        maxAnswers: 2,
        prompts: [
            "___ the company has invested heavily in sustainability, its carbon emissions have increased due to rapid growth.",
            "___ the school upgraded its digital infrastructure, many teachers still rely on traditional methods.",
            "___ the city expanded its public transport network, traffic congestion remains a major issue.",
            "___ the team trained intensively for months, their performance in the tournament was disappointing.",
            "___ the government introduced strict environmental regulations, pollution levels have barely decreased.",
            "___ the university increased its scholarship offerings, many students still struggle to afford tuition.",
            "___ the retailer launched a major advertising campaign, sales have not improved significantly.",
            "___ the hospital hired additional staff, waiting times in the emergency department remain long.",
            "___ the brand redesigned its website, users continue to report navigation difficulties.",
            "___ the airline improved its customer service training, complaints about delays remain high.",
            "___ the museum added several new exhibits, visitor numbers have not increased noticeably.",
            "___ the company boosted its research budget, innovation output has stayed relatively low.",
            "___ the school reduced class sizes, academic performance has not improved as expected.",
            "___ the city built new bike lanes, most residents still prefer to drive short distances.",
            "___ the team developed a new strategy, the same mistakes keep appearing in matches.",
            "___ the organization raised substantial funds, its outreach programs remain understaffed.",
            "___ the café introduced a healthier menu, regular customers still choose the older options.",
            "___ the firm adopted a flexible work policy, some employees feel disconnected from their teams.",
            "___ the country invested heavily in renewable energy, fossil fuels still dominate its energy mix.",
            "___ the startup secured significant venture funding, it continues to struggle with scaling operations.",
            "___ the company expanded its customer‑service team, response times have not improved noticeably.",
            "___ the school introduced a new reading program, literacy scores have remained largely unchanged.",
            "___ the city invested in renewable energy, overall emissions have continued to rise.",
            "___ the team recruited several talented players, their overall performance has stayed inconsistent.",
            "___ the government increased funding for public transport, many commuters still rely on cars.",
            "___ the university renovated its science labs, enrollment in STEM programs has not grown.",
            "___ the retailer lowered prices across multiple categories, customer traffic remains low.",
            "___ the hospital implemented new safety protocols, minor incidents still occur regularly.",
            "___ the organization launched a major awareness campaign, public engagement has been limited.",
            "___ the café extended its opening hours, evening sales have not increased as expected."
                    ]
    }

}